REBEL_SHIP = {
    back = "https://i.imgur.com/vUaQViH.png",
    faction = "Rebellion"
}
Ship:new(SmallShip,REBEL_SHIP,{
	name = "GR-75 Medium Transports",
    front = "https://i.imgur.com/vMgbQB3.png",
    mesh = "http://paste.ee/p/XZLIh",
    diffuse = "http://i.imgur.com/2A2pAEI.png",
    ruler = "http://paste.ee/r/FSip2",
    maneuver = {{"II"},{"I","II"},{"-","I","II"}},
    defense_tokens = {DEF_SCATTER, DEF_EVADE},
    shields = {1,1,1,1},
    cost = 18,
    aliases = {},
    command = 1
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "GR-75 Combat Retrofits",
    front = "https://i.imgur.com/GmEEfVA.png",
    mesh = "http://paste.ee/p/XZLIh",
    diffuse = "http://i.imgur.com/dO7rAWL.png",
    ruler = "http://paste.ee/r/FSip2",
    maneuver = {{"II"},{"I","II"},{"-","I","II"}},
    defense_tokens = {DEF_SCATTER, DEF_EVADE},
    shields = {1,1,1,1},
    cost = 24,
    aliases = {},
    command = 1
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "CR90 Corvette A",
    front = "https://i.imgur.com/bobtrD0.png",
    mesh = "http://paste.ee/r/ciL22",
    diffuse = "http://i.imgur.com/0kAY3h2.png",
    ruler = "http://paste.ee/r/H13ZL",
    maneuver = {{"II"},{"I","II"},{"-","I","II"},{"-","I","I","II"}},
    defense_tokens = {DEF_EVADE, DEF_EVADE, DEF_REDIRECT},
    shields = {2,2,2,1},
    cost = 44,
    aliases = {"CR90 A"},
    command = 1
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "CR90 Corvette B",
    front = "https://i.imgur.com/ff7qkS5.png",
    mesh = "http://paste.ee/r/ciL22",
    diffuse = "http://i.imgur.com/k7I0BOQ.png",
    ruler = "http://paste.ee/r/H13ZL",
    maneuver = {{"II"},{"I","II"},{"-","I","II"},{"-","I","I","II"}},
    defense_tokens = {DEF_EVADE, DEF_EVADE, DEF_REDIRECT},
    shields = {2,2,2,1},
    cost = 39,
    aliases = {"CR90 B"},
    command = 1
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "Nebulon-B Support Refit",
    front = "https://i.imgur.com/Htpwn5Q.png",
    mesh = "http://paste.ee/r/5jlFC",
    diffuse = "http://i.imgur.com/4LZROT5.png",
    ruler = "http://paste.ee/r/xI908",
    maneuver = {{"I"},{"I","I"},{"-","I","II"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_BRACE},
    shields = {3,1,1,2},
    cost = 51,
    aliases = {},
    command = 2
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "Nebulon-B Escort Frigate",
    front = "https://i.imgur.com/hnEKY1U.png",
    mesh = "http://paste.ee/r/5jlFC",
    diffuse = "http://i.imgur.com/avcsD9I.png",
    ruler = "http://paste.ee/r/xI908",
    maneuver = {{"I"},{"I","I"},{"-","I","II"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_BRACE},
    shields = {3,1,1,2},
    cost = 57,
    aliases = {},
    command = 2
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "MC30c Scout Frigate",
    front = "https://i.imgur.com/L3532U9.png",
    mesh = "http://paste.ee/r/DGrIr",
    diffuse = "http://i.imgur.com/nxIAPfN.jpg",
    ruler = "http://paste.ee/r/g71A1",
    maneuver = {{"I"},{"I","I"},{"-","I","II"},{"-","I","I","-"}},
    defense_tokens = {DEF_EVADE, DEF_EVADE, DEF_REDIRECT, DEF_REDIRECT},
    shields = {3,3,3,2},
    cost = 69,
    aliases = {},
    command = 2
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "MC30c Torpedo Frigate",
    front = "https://i.imgur.com/RG0ttdp.png",
    mesh = "http://paste.ee/r/DGrIr",
    diffuse = "http://i.imgur.com/GOBHwVr.jpg",
    ruler = "http://paste.ee/r/g71A1",
    maneuver = {{"I"},{"I","I"},{"-","I","II"},{"-","I","I","-"}},
    defense_tokens = {DEF_EVADE, DEF_EVADE, DEF_REDIRECT, DEF_REDIRECT},
    shields = {3,3,3,2},
    cost = 63,
    aliases = {},
    command = 2
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "Modified Pelta-class Command Ship",
    front = "https://i.imgur.com/x6gMgaX.png",
    mesh = "https://paste.ee/p/4QYyI",
    diffuse = "http://i.imgur.com/aiGsc3c.jpg",
    ruler = "http://paste.ee/p/RDjaZ",
    maneuver = {{"II"},{"I","I"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_REDIRECT},
    shields = {3,2,2,1},
    cost = 60,
    aliases = {"Modified Pelta Command Ship", "Pelta Command Ship"},
    command = 2
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "Modified Pelta-class Assault Ship",
    front = "https://i.imgur.com/fw4TbCR.png",
    mesh = "https://paste.ee/p/4QYyI",
    diffuse = "http://i.imgur.com/wIVRRW3.jpg",
    ruler = "http://paste.ee/p/RDjaZ",
    maneuver = {{"II"},{"I","I"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_REDIRECT},
    shields = {3,2,2,1},
    cost = 56,
    aliases = {"Modified Pelta Assault Ship", "Pelta Assault Ship"},
    command = 2
})

Ship:new(SmallShip,REBEL_SHIP,{
	name = "Hammerhead Scout Corvette",
    front = "https://i.imgur.com/QcTmlXq.png",
    mesh = "http://paste.ee/r/jI2Qo",
    diffuse = "http://i.imgur.com/cxOtWAb.jpg",
    ruler = "http://paste.ee/p/DA9vu",
    maneuver = {{"II"},{"II","I"},{"I","I","-"}},
    defense_tokens = {DEF_EVADE, DEF_REDIRECT, DEF_CONTAIN},
    shields = {2,1,1,1},
    cost = 41,
    aliases = {},
    command = 1
})
Ship:new(SmallShip,REBEL_SHIP,{
	name = "Hammerhead Torpedo Corvette",
    front = "https://i.imgur.com/h8DWzpu.png",
    mesh = "http://paste.ee/r/jI2Qo",
    diffuse = "http://i.imgur.com/v3KSaTf.jpg",
    ruler = "http://paste.ee/p/DA9vu",
    maneuver = {{"II"},{"II","I"},{"I","I","-"}},
    defense_tokens = {DEF_EVADE, DEF_REDIRECT, DEF_CONTAIN},
    shields = {2,1,1,1},
    cost = 36,
    aliases = {},
    command = 1
})

Ship:new(MediumShip,REBEL_SHIP,{
	name = "Assault Frigate Mark II A",
    front = "https://i.imgur.com/XXIO5qw.png",
    mesh = "http://paste.ee/r/zNWBM",
    diffuse = "http://i.imgur.com/vreFbKa.jpg",
    ruler = "http://paste.ee/r/kmnpd",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_REDIRECT},
    shields = {4,3,3,2},
    cost = 81,
    aliases = {"Assault Frigate Mk.II A","Assault Frigate MkII A","Assault Frigate Mk2 A"},
    command = 3
})
Ship:new(MediumShip,REBEL_SHIP,{
	name = "Assault Frigate Mark II B",
    front = "https://i.imgur.com/LsxALho.png",
    mesh = "http://paste.ee/r/zNWBM",
    diffuse = "http://i.imgur.com/l2L9TXv.jpg",
    ruler = "http://paste.ee/r/kmnpd",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_EVADE, DEF_BRACE, DEF_REDIRECT},
    shields = {4,3,3,2},
    cost = 72,
    aliases = {"Assault Frigate Mk.II B","Assault Frigate MkII B","Assault Frigate Mk2 B"},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC80 Command Cruiser",
    front = "https://i.imgur.com/zJfyMXV.png",
    mesh = "http://paste.ee/r/am8JC",
    diffuse = "http://i.imgur.com/pW1iM1a.png",
    ruler = "http://paste.ee/r/YcTl3",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_REDIRECT, DEF_CONTAIN},
    shields = {4,4,4,3},
    cost = 106,
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC80 Assault Cruiser",
    front = "https://i.imgur.com/vC6SfGR.png",
    mesh = "http://paste.ee/r/am8JC",
    diffuse = "http://i.imgur.com/xklILcW.png",
    ruler = "http://paste.ee/r/YcTl3",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_REDIRECT, DEF_CONTAIN},
    shields = {4,4,4,3},
    cost = 114,
    aliases = {},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC80 Star Cruiser",
    front = "https://i.imgur.com/bEDTEFP.png",
    mesh = "http://paste.ee/r/eEzbI",
    diffuse = "http://i.imgur.com/Cb3Nexq.png",
    ruler = "http://paste.ee/r/XjDg0",
    maneuver = {{"I"},{"I","-"},{"I","-","I"}},
    defense_tokens = {DEF_BRACE, DEF_BRACE, DEF_REDIRECT},
    shields = {5,2,2,2},
    cost = 96,
    aliases = {},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC80 Battle Cruiser",
    front = "https://i.imgur.com/Xij4Ufr.png",
    mesh = "http://paste.ee/r/eEzbI",
    diffuse = "http://i.imgur.com/DHGrZcJ.png",
    ruler = "http://paste.ee/r/XjDg0",
    maneuver = {{"I"},{"I","-"},{"I","-","I"}},
    defense_tokens = {DEF_BRACE, DEF_BRACE, DEF_REDIRECT},
    shields = {5,2,2,2},
    cost = 103,
    aliases = {},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC75 Ordnance Cruiser",
    front = "https://i.imgur.com/L9piyH4.png",
    mesh = "http://paste.ee/r/tdeQQ",
    diffuse = "http://i.imgur.com/ijSlgsR.jpg",
    ruler = "http://paste.ee/r/qw6fH",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_CONTAIN, DEF_CONTAIN},
    shields = {4,3,3,3},
    cost = 100,
    aliases = {},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "MC75 Armored Cruiser",
    front = "https://i.imgur.com/sLecO5b.png",
    mesh = "http://paste.ee/r/tdeQQ",
    diffuse = "http://i.imgur.com/lLjEVbO.jpg",
    ruler = "http://paste.ee/r/qw6fH",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_CONTAIN, DEF_CONTAIN},
    shields = {4,3,3,3},
    cost = 104,
    aliases = {},
    command = 3
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "Starhawk-class Battleship Mark I",
    front = "https://i.imgur.com/xJIm5pQ.png",
    mesh = "http://paste.ee/p/70TGL",
    diffuse = "http://i.imgur.com/15ng8Hn.jpg",
    ruler = "http://paste.ee/p/TFbWH",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_CONTAIN, DEF_SALVO},
    shields = {6,4,4,2},
    cost = 140,
    aliases = {"Starhawk Battleship Mark I", "Starhawk-class Battleship Mk.I", "Starhawk-class Battleship MkI", "Starhawk-class Mk.I", "Starhawk-class MkI"},
    command = 4
})
Ship:new(LargeShip,REBEL_SHIP,{
	name = "Starhawk-class Battleship Mark II",
    front = "https://i.imgur.com/VZFlC1M.png",
    mesh = "http://paste.ee/p/70TGL",
    diffuse = "http://i.imgur.com/e61Q601.jpg",
    ruler = "http://paste.ee/p/TFbWH",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_CONTAIN, DEF_SALVO},
    shields = {6,4,4,2},
    cost = 150,
    aliases = {"Starhawk Battleship Mark II", "Starhawk-class Battleship Mk.II", "Starhawk-class Battleship MkII", "Starhawk-class Mk.II", "Starhawk-class MkII"},
    command = 4
})
