REBEL_SQUAD = {
    back = "https://i.imgur.com/8s63Ngl.png"
}
ship = {
    mesh = "http://paste.ee/r/ZqCC6",
    diffuse = "http://i.imgur.com/QSLaqgW.png",
    health = 5,
    move = 2,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "B-wing Squadron",
    front = "https://i.imgur.com/bB11RGw.png",
    cost = 14
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Keyan Farlander",
    front = "https://i.imgur.com/r4bx4xg.png",
    diffuse = "http://i.imgur.com/r7YB80F.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 20
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Ten Numb",
    front = "https://i.imgur.com/8zae2YW.png",
    diffuse = "http://i.imgur.com/r7YB80F.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 19
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Dagger Squadron",
    front = "https://i.imgur.com/41kkBy6.png",
    diffuse = "http://i.imgur.com/swXemsa.png",
    mesh = "http://paste.ee/p/NpCQt",
    cost = 15
})
ship = {
    mesh = "http://paste.ee/r/AG2g4",
    diffuse = "http://i.imgur.com/ObUEAK5.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "Y-wing Squadron",
    front = "https://i.imgur.com/20kwNNs.png",
    cost = 10
})
Squadron:new(ship, REBEL_SQUAD, {
	name = '"Dutch" Vander',
    front = "https://i.imgur.com/97UoG34.png",
    diffuse = "http://i.imgur.com/pRu0c7d.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 16
})
Squadron:new(ship, REBEL_SQUAD, {
	name = 'Norra Wexley',
    front = "https://i.imgur.com/VlUNCkM.png",
    diffuse = "http://i.imgur.com/pRu0c7d.png",
    mesh = "http://paste.ee/p/5i0Ma",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 17
})
Squadron:new(ship, REBEL_SQUAD, {
	name = 'Gold Squadron',
    front = "https://i.imgur.com/m6efvmr.png",
    mesh = "http://paste.ee/p/5i0Ma",
    diffuse = "http://i.imgur.com/pRu0c7d.png",
    cost = 12
})
ship = {
    mesh = "http://paste.ee/r/3Wdv8",
    diffuse = "http://i.imgur.com/6vlNuEY.png",
    health = 4,
    move = 5,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "A-wing Squadron",
    front = "https://i.imgur.com/JikzQGo.png",
    cost = 11
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Tycho Celchu",
    front = "https://i.imgur.com/XsXiGTU.png",
    diffuse = "http://i.imgur.com/QZPi4e7.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 16
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Shara Bey",
    front = "https://i.imgur.com/QhDp5hB.png",
    diffuse = "http://i.imgur.com/QZPi4e7.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 17
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Green Squadron",
    front = "https://i.imgur.com/a00ZFfc.png",
    mesh = "http://paste.ee/p/ybtPs",
    diffuse = "http://i.imgur.com/0awlEmY.png",
    cost = 12
})
ship = {
    mesh = "http://paste.ee/r/zjUF1",
    diffuse = "http://i.imgur.com/HHbQ8lf.png",
    health = 5,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "X-wing Squadron",
    front = "https://i.imgur.com/d5QuMBy.png",
    cost = 13
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Luke Skywalker",
    front = "https://i.imgur.com/CcTsLiM.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 20
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Wedge Antilles",
    front = "https://i.imgur.com/uepzi7O.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 19
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Biggs Darklighter",
    front = "https://i.imgur.com/zLMC2Fc.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 19
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Rogue Squadron",
    front = "https://i.imgur.com/A1IByHc.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    mesh = "http://paste.ee/p/PsdOf",
    cost = 14
})
ship = {
    mesh = "http://paste.ee/r/919yT",
    diffuse = "http://i.imgur.com/P11kSne.png",
    health = 6,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "YT-2400",
    front = "https://i.imgur.com/Ui3LTlu.png",
    cost = 16
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Dash Rendar",
    front = "https://i.imgur.com/7TfYFsY.png",
    mesh = "http://paste.ee/r/V5oHI",
    diffuse = "http://i.imgur.com/3iJ0Wxe.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 24
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Mart Mattin",
    front = "https://i.imgur.com/UyCPNqt.png",
    mesh = "http://paste.ee/p/4qSjx",
    diffuse = "http://i.imgur.com/3iJ0Wxe.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 22
})
ship = {
    mesh = "http://paste.ee/r/hhbic",
    diffuse = "http://i.imgur.com/bndtRkF.png",
    health = 7,
    move = 2,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "YT-1300",
    front = "https://i.imgur.com/pFKaprO.png",
    cost = 13
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Han Solo",
    front = "https://i.imgur.com/8ni1bSl.png",
    mesh = "http://paste.ee/r/6yDva",
    diffuse = "http://i.imgur.com/v16flTU.png",
    move = 3,
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 26
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Lando Calrissian",
    front = "https://i.imgur.com/Xk43ysd.png",
    mesh = "http://paste.ee/r/6yDva",
    diffuse = "http://i.imgur.com/v16flTU.png",
    move = 3,
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 23
})
ship = {
    mesh = "http://paste.ee/r/DURQd",
    diffuse = "http://i.imgur.com/03TMKSR.png",
    health = 4,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "HWK-290",
    front = "https://i.imgur.com/Zm7888b.png",
    cost = 12
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Jan Ors",
    front = "https://i.imgur.com/NQqAVr8.png",
    diffuse = "http://i.imgur.com/bnknApA.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 19
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Kanan Jarrus",
    front = "https://i.imgur.com/Cpp6DXG.png",
    mesh = "http://paste.ee/p/csGHI",
    diffuse = "http://i.imgur.com/bnknApA.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 19
})
ship = {
    mesh = "http://paste.ee/r/dvrOX",
    diffuse = "http://i.imgur.com/4Stv3go.png",
    health = 6,
    move = 3 }
Squadron:new(ship, REBEL_SQUAD, {
	name = "Scurrg H-6 Bomber",
    front = "https://i.imgur.com/QvhGpkj.png",
    cost = 16
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Nym",
    front = "https://i.imgur.com/vfrMC1z.png",
    mesh = "http://paste.ee/r/96QNu",
    diffuse = "http://i.imgur.com/QAaYYfU.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 21
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Malee Hurra",
    front = "https://i.imgur.com/JmifVSX.png",
    mesh = "http://paste.ee/r/96QNu",
    diffuse = "http://i.imgur.com/QAaYYfU.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 26
})
ship = {
    mesh = "http://paste.ee/p/ZHpHT",
    diffuse = "http://i.imgur.com/zYmUqph.png",
    health = 3,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "Z-95 Headhunter Squadron",
    front = "https://i.imgur.com/o3ydY6G.png",
    cost = 7
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Lieutenant Blount",
    front = "https://i.imgur.com/dlts7hE.png",
    diffuse = "http://i.imgur.com/aTuRbPL.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 14
})
ship = {
    mesh = "http://paste.ee/p/ElhHc",
    diffuse = "http://i.imgur.com/X9E1n2M.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "E-wing Squadron",
    front = "https://i.imgur.com/iDlDpb3.png",
    cost = 15
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Corran Horn",
    front = "https://i.imgur.com/r9KN0kh.png",
    mesh = "http://paste.ee/p/r2fsB",
    diffuse = "http://i.imgur.com/3uSFKMb.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 22
})
ship = {
    mesh = "http://paste.ee/p/3QIXa",
    diffuse = "http://i.imgur.com/5UVGuIg.png",
    health = 8,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "VCX-100 Freighter",
    front = "https://i.imgur.com/CmvkFAq.png",
    cost = 15
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Hera Syndulla",
    front = "https://i.imgur.com/b5rhKSS.png",
    mesh = "http://paste.ee/p/3NpiT",
    diffuse = "http://i.imgur.com/wPzX0MW.png",
    defense_tokens = {DEF_BRACE},
    cost = 28
})
ship = {
    mesh = "http://paste.ee/p/L9ygS",
    diffuse = "http://i.imgur.com/CZ3eF4M.png",
    health = 4,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, REBEL_SQUAD, {
	name = "Lancer-class Pursuit Craft",
    front = "https://i.imgur.com/qDSMy7N.png",
    cost = 15
})
Squadron:new(ship, REBEL_SQUAD, {
	name = "Ketsu Onyo",
    front = "https://i.imgur.com/97603QH.png",
    diffuse = "http://i.imgur.com/eJxMrk2.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 22
})
