REBEL_SQUAD = {
    back = "https://i.imgur.com/8s63Ngl.png"
}
ship = {
    mesh = "http://paste.ee/r/ZqCC6",
    diffuse = "http://i.imgur.com/QSLaqgW.png",
    health = 5,
    move = 2,
    defense_tokens = {}}
SHIPS["B-wing Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/bB11RGw.png"
})
SHIPS["Keyan Farlander"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/r4bx4xg.png",
    diffuse = "http://i.imgur.com/r7YB80F.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Ten Numb"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/8zae2YW.png",
    diffuse = "http://i.imgur.com/r7YB80F.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Dagger Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/41kkBy6.png",
    diffuse = "http://i.imgur.com/swXemsa.png",
    mesh = "http://paste.ee/p/NpCQt"
})
ship = {
    mesh = "http://paste.ee/r/AG2g4",
    diffuse = "http://i.imgur.com/ObUEAK5.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
SHIPS["Y-wing Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/20kwNNs.png"
})
SHIPS['"Dutch" Vander'] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/97UoG34.png",
    diffuse = "http://i.imgur.com/pRu0c7d.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS['Norra Wexley'] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/VlUNCkM.png",
    diffuse = "http://i.imgur.com/pRu0c7d.png",
    mesh = "http://paste.ee/p/5i0Ma",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS['Gold Squadron'] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/m6efvmr.png",
    mesh = "http://paste.ee/p/5i0Ma",
    diffuse = "http://i.imgur.com/pRu0c7d.png"
})
ship = {
    mesh = "http://paste.ee/r/3Wdv8",
    diffuse = "http://i.imgur.com/6vlNuEY.png",
    health = 4,
    move = 5,
    defense_tokens = {}}
SHIPS["A-wing Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/JikzQGo.png"
})
SHIPS["Tycho Celchu"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/XsXiGTU.png",
    diffuse = "http://i.imgur.com/QZPi4e7.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS["Shara Bey"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/QhDp5hB.png",
    diffuse = "http://i.imgur.com/QZPi4e7.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS["Green Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/a00ZFfc.png",
    mesh = "http://paste.ee/p/ybtPs",
    diffuse = "http://i.imgur.com/0awlEmY.png"
})
ship = {
    mesh = "http://paste.ee/r/zjUF1",
    diffuse = "http://i.imgur.com/HHbQ8lf.png",
    health = 5,
    move = 3,
    defense_tokens = {}}
SHIPS["X-wing Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/d5QuMBy.png"
})
SHIPS["Luke Skywalker"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/CcTsLiM.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Wedge Antilles"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/uepzi7O.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Biggs Darklighter"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/zLMC2Fc.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Rogue Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/A1IByHc.png",
    diffuse = "http://i.imgur.com/6xKSmMQ.png",
    mesh = "http://paste.ee/p/PsdOf"
})
ship = {
    mesh = "http://paste.ee/r/919yT",
    diffuse = "http://i.imgur.com/P11kSne.png",
    health = 6,
    move = 4,
    defense_tokens = {}}
SHIPS["YT-2400"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/Ui3LTlu.png"
})
SHIPS["Dash Rendar"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/7TfYFsY.png",
    mesh = "http://paste.ee/r/V5oHI",
    diffuse = "http://i.imgur.com/3iJ0Wxe.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Mart Mattin"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/UyCPNqt.png",
    mesh = "http://paste.ee/p/4qSjx",
    diffuse = "http://i.imgur.com/3iJ0Wxe.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/r/hhbic",
    diffuse = "http://i.imgur.com/bndtRkF.png",
    health = 7,
    move = 2,
    defense_tokens = {}}
SHIPS["YT-1300"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/pFKaprO.png"
})
SHIPS["Han Solo"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/8ni1bSl.png",
    mesh = "http://paste.ee/r/6yDva",
    diffuse = "http://i.imgur.com/v16flTU.png",
    move = 3,
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Lando Calrissian"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/Xk43ysd.png",
    mesh = "http://paste.ee/r/6yDva",
    diffuse = "http://i.imgur.com/v16flTU.png",
    move = 3,
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/r/DURQd",
    diffuse = "http://i.imgur.com/03TMKSR.png",
    health = 4,
    move = 3,
    defense_tokens = {}}
SHIPS["HWK-290"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/Zm7888b.png"
})
SHIPS["Jan Ors"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/NQqAVr8.png",
    diffuse = "http://i.imgur.com/bnknApA.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Kanan Jarrus"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/Cpp6DXG.png",
    mesh = "http://paste.ee/p/csGHI",
    diffuse = "http://i.imgur.com/bnknApA.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/r/dvrOX",
    diffuse = "http://i.imgur.com/4Stv3go.png",
    health = 6,
    move = 3 }
SHIPS["Scurrg H-6 Bomber"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/QvhGpkj.png"
})
SHIPS["Nym"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/vfrMC1z.png",
    mesh = "http://paste.ee/r/96QNu",
    diffuse = "http://i.imgur.com/QAaYYfU.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Malee Hurra"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/JmifVSX.png",
    mesh = "http://paste.ee/r/96QNu",
    diffuse = "http://i.imgur.com/QAaYYfU.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/ZHpHT",
    diffuse = "http://i.imgur.com/zYmUqph.png",
    health = 3,
    move = 3,
    defense_tokens = {}}
SHIPS["Z-95 Headhunter Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/o3ydY6G.png"
})
SHIPS["Lieutenant Blount"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/dlts7hE.png",
    diffuse = "http://i.imgur.com/aTuRbPL.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
ship = {
    mesh = "http://paste.ee/p/ElhHc",
    diffuse = "http://i.imgur.com/X9E1n2M.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
SHIPS["E-wing Squadron"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/iDlDpb3.png"
})
SHIPS["Corran Horn"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/r9KN0kh.png",
    mesh = "http://paste.ee/p/r2fsB",
    diffuse = "http://i.imgur.com/3uSFKMb.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/3QIXa",
    diffuse = "http://i.imgur.com/5UVGuIg.png",
    health = 8,
    move = 3,
    defense_tokens = {}}
SHIPS["VCX-100 Freighter"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/CmvkFAq.png"
})
SHIPS["Hera Syndulla"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/b5rhKSS.png",
    mesh = "http://paste.ee/p/3NpiT",
    diffuse = "http://i.imgur.com/wPzX0MW.png",
    defense_tokens = {DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/L9ygS",
    diffuse = "http://i.imgur.com/CZ3eF4M.png",
    health = 4,
    move = 4,
    defense_tokens = {}}
SHIPS["Lancer-class Pursuit Craft"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/qDSMy7N.png"
})
SHIPS["Ketsu Onyo"] = Squadron:new(ship, REBEL_SQUAD, {
    front = "https://i.imgur.com/97603QH.png",
    diffuse = "http://i.imgur.com/eJxMrk2.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
