Objective = {
    type="Objective",
    back = "https://i.imgur.com/6mOLyyo.jpeg"
}

Assault = { category = "Assault" }
Card:new(Assault, Objective, {name="Advanced Gunnery", front="https://i.imgur.com/3dV3CQL.png"})
Card:new(Assault, Objective, {name="Blockade Run", front="https://i.imgur.com/uy3nABn.png", victory=20})
Card:new(Assault, Objective, {name="Close-Range Intel Scan", front="https://i.imgur.com/metfsL6.png", victory=10})
Card:new(Assault, Objective, {name="Ion Storm", front="https://i.imgur.com/EvRHvo6.png", victory=15})
Card:new(Assault, Objective, {name="Marked for Destruction", front="https://i.imgur.com/Jl513DV.png", victory=15})
Card:new(Assault, Objective, {name="Most Wanted", front="https://i.imgur.com/AYUAvDe.png"})
Card:new(Assault, Objective, {name="Opening Salvo", front="https://i.imgur.com/mU3mg9Y.png"})
Card:new(Assault, Objective, {name="Precision Strike", front="https://i.imgur.com/5PrHKKV.png", victory=15})
Card:new(Assault, Objective, {name="Rift Assault", front="https://i.imgur.com/h0sCMti.png", victory=10})
Card:new(Assault, Objective, {name="Station Assault", front="https://i.imgur.com/RZQ6WiC.png", victory=40})
Card:new(Assault, Objective, {name="[Ship Card] Unarmed Station", front="https://i.imgur.com/pr34PEA.jpeg"})
Card:new(Assault, Objective, {name="Surprise Attack", front="https://i.imgur.com/WAg0yAC.png"})
Card:new(Assault, Objective, {name="Targeting Beacons", front="https://i.imgur.com/hkF4kTT.png"})

Defense = { category = "Defense" }
Card:new(Defense, Objective, {name="Abandoned Mining Facility", front="https://i.imgur.com/FisDnrA.png", victory=10})
Card:new(Defense, Objective, {name="Asteroid Tactics", front="https://i.imgur.com/FDqrQoA.png"})
Card:new(Defense, Objective, {name="Capture the VIP", front="https://i.imgur.com/LKfjSzk.png", victory=50})
Card:new(Defense, Objective, {name="Contested Outpost", front="https://i.imgur.com/Ksycqqu.png", victory=20})
Card:new(Defense, Objective, {name="Fighter Ambush", front="https://i.imgur.com/QcWcYBQ.png", victory=15})
Card:new(Defense, Objective, {name="Fire Lanes", front="https://i.imgur.com/1d7wzLM.png", victory=15})
Card:new(Defense, Objective, {name="Fleet Ambush", front="https://i.imgur.com/vm9LLJo.png"})
Card:new(Defense, Objective, {name="Fleet in Being", front="https://i.imgur.com/GIX4wWL.png", victory=15})
Card:new(Defense, Objective, {name="Hyperspace Assault", front="https://i.imgur.com/GqjQIK3.png"})
Card:new(Defense, Objective, {name="Jamming Barrier", front="https://i.imgur.com/hNJ6INI.png"})
Card:new(Defense, Objective, {name="Planetary Ion Cannon", front="https://i.imgur.com/psjZcZb.png"})
Card:new(Defense, Objective, {name="Rift Ambush", front="https://i.imgur.com/a2rih6q.png"})

Navigation = { category = "Navigation" }
Card:new(Navigation, Objective, {name="Dangerous Territory", front="https://i.imgur.com/DIlMCHD.png", victory=15})
Card:new(Navigation, Objective, {name="Doomed Station", front="https://i.imgur.com/SZ8kaLu.png", victory=20})
Card:new(Navigation, Objective, {name="Hyperspace Migration", front="https://i.imgur.com/oQO2QV0.png", victory=20})
Card:new(Navigation, Objective, {name="Infested Fields", front="https://i.imgur.com/FrULG6O.png", victory=15})
Card:new(Navigation, Objective, {name="Intel Sweep", front="https://i.imgur.com/whvJxjk.png"})
Card:new(Navigation, Objective, {name="Minefields", front="https://i.imgur.com/9HOIdHa.png"})
Card:new(Navigation, Objective, {name="Navigational Hazards", front="https://i.imgur.com/FaFVElY.png", victory=15})
Card:new(Navigation, Objective, {name="Salvage Run", front="https://i.imgur.com/VLUPsmd.png", victory=20})
Card:new(Navigation, Objective, {name="Sensor Net", front="https://i.imgur.com/tLdaZPu.png", victory=15})
Card:new(Navigation, Objective, {name="Solar Corona", front="https://i.imgur.com/7YfXYte.png"})
Card:new(Navigation, Objective, {name="Superior Positions", front="https://i.imgur.com/eL4Ow8N.png", victory=15})
Card:new(Navigation, Objective, {name="Volatile Deposits", front="https://i.imgur.com/tiR18cD.png", victory=15})

Special = { category = "Special" }
Card:new(Special, Objective, {name="Base Defense: Armed Station", front="https://i.imgur.com/uuS6Bgr.png"})
Card:new(Special, Objective, {name="[Ship Card] Armed Station", front="https://i.imgur.com/8bxI1du.jpeg"})
Card:new(Special, Objective, {name="Base Defense: Fighter Wing", front="https://i.imgur.com/HSGDnta.png"})
Card:new(Special, Objective, {name="Base Defense: Ion Cannon", front="https://i.imgur.com/qpZfp8c.png"})
Card:new(Special, Objective, {name="Hyperlane Raid", front="https://i.imgur.com/vqS5veh.png", victory=15})
Card:new(Special, Objective, {name="Show of Force", front="https://i.imgur.com/GJvRA00.png", victory=20})
--Corellian Conflict
Card:new(Special, Objective, {name="Asteroids", front="https://i.imgur.com/u27Su4O.png"})
Card:new(Special, Objective, {name="Independent Station", front="https://i.imgur.com/I08mCTY.png"})
Card:new(Special, Objective, {name="Nebula Outskirts", front="https://i.imgur.com/60jSGex.png"})
--Rebellion in the Rim
Card:new(Special, Objective, {name="Double Agent", front="https://i.imgur.com/gsxsug1.png", victory=20})
Card:new(Special, Objective, {name="Hired Scum", front="https://i.imgur.com/uSeL1Iv.png"})
Card:new(Special, Objective, {name="Holonet Override", front="https://i.imgur.com/2DnZ1Ha.png", victory=10})
Card:new(Special, Objective, {name="Pilot Defection", front="https://i.imgur.com/p4tl1sP.png", victory=25})
Card:new(Special, Objective, {name="Prototype Recovery", front="https://i.imgur.com/QIaiFWk.png", victory=30})
Card:new(Special, Objective, {name="Recruit Allies", front="https://i.imgur.com/9PqROM7.png"})
Card:new(Special, Objective, {name="Steal Supplies", front="https://i.imgur.com/ytyYixO.png", victory=15})
Card:new(Special, Objective, {name="Volatile Cargo", front="https://i.imgur.com/N0MR24N.png", victory=15})

Card:new(Special, Objective, {name="Low Fuel", front="https://i.imgur.com/L5Vpk1x.jpeg"})
Card:new(Special, Objective, {name="Low Morale", front="https://i.imgur.com/pVL0ttA.jpeg"})
Card:new(Special, Objective, {name="Low Supplies", front="https://i.imgur.com/TdrrOqs.jpeg"})
