Commander = {
    type="Commander"
    back = ""
}
function Commander:new (o)
    o = o or {}
    setmetatable(o, Commander)
    Commander.__index = Commander
    CARDS[o.Name.." ("..o.type..")"] = o
    return o
end
--rebel
Commander:new{name="Admiral Ackbar",  front="http://i.imgur.com/HFVv48K.jpg"}
Commander:new{name="Admiral Raddus",  front="http://i.imgur.com/2IPtau4.jpg"}
Commander:new{name="Garm Bel Iblis",  front="http://i.imgur.com/fmlXop3.jpg"}
Commander:new{name="General Cracken",  front="http://i.imgur.com/0NHwrEL.jpg"}
Commander:new{name="General Dodonna",  front="http://i.imgur.com/MsS9AN8.jpg"}
Commander:new{name="General Madine",  front="http://i.imgur.com/ePeK8Ok.jpg"}
Commander:new{name="General Rieekan",  front="http://i.imgur.com/Q6pSiLj.jpg"}
Commander:new{name="Kyrsta Agate",  front="http://i.imgur.com/CdWKsAz.jpg"}
Commander:new{name="Leia Organa",  front="http://i.imgur.com/Xsqh5f0.jpg"}
Commander:new{name="Mon Mothma",  front="http://i.imgur.com/ZK3rQeb.jpg"}

--imperial
Commander:new{name="Admiral Konstantine",  front="http://i.imgur.com/ONoTDBL.jpg"}
Commander:new{name="Admiral Motti",  front="http://i.imgur.com/rkMe17G.jpg"}
Commander:new{name="Admiral Ozzel",  front="http://i.imgur.com/v0nThwx.jpg"}
Commander:new{name="Admiral Piett",  front="http://i.imgur.com/2D3DgQS.jpg"}
Commander:new{name="Admiral Screed",  front="http://i.imgur.com/DUToctV.jpg"}
Commander:new{name="Admiral Sloane",  front="http://i.imgur.com/rzZtf8B.jpg"}
Commander:new{name="Commander Sato",  front="http://i.imgur.com/ir6QixK.jpg"}
Commander:new{name="Darth Vader",  front="http://i.imgur.com/ysyfpEF.jpg"}
Commander:new{name="Emperor Palpatine",  front="http://i.imgur.com/KBY36Qs.jpg"}
Commander:new{name="General Romodi",  front="http://i.imgur.com/U9wK3K8.jpg"}
Commander:new{name="General Tagge",  front="http://i.imgur.com/LduHiR8.jpg"}
Commander:new{name="Grand Admiral Thrawn",  front="http://i.imgur.com/FSpE1gl.jpg"}
Commander:new{name="Grand Moff Tarkin",  front="http://i.imgur.com/OxvHWmA.jpg"}
Commander:new{name="Moff Jerjerrod",  front="http://i.imgur.com/qZAVH6a.jpg"}

--republic
Commander:new{name="Bail Organa",  front="https://i.imgur.com/SBYa2yD.jpeg"}
Commander:new{name="Obi-Wan Kenobi",  front="https://i.imgur.com/xkfBnRw.jpeg"}

--separatist
Commander:new{name="Count Dooku",  front="https://i.imgur.com/YOm4LIi.jpeg"}
Commander:new{name="Kraken",  front="https://i.imgur.com/zLNsrOo.jpeg"}
