Commander = {
    type="Commander",
    back = "https://i.imgur.com/fMJMaYo.png"
}
--rebel
Rebel = {
    factions={"Rebellion"}
}
Card:new(Commander,Rebel,{name="Admiral Ackbar",  front="http://i.imgur.com/HFVv48K.jpg", cost=38})
Card:new(Commander,Rebel,{name="Admiral Raddus",  front="http://i.imgur.com/2IPtau4.jpg", cost=26})
Card:new(Commander,Rebel,{name="Commander Sato",  front="http://i.imgur.com/ir6QixK.jpg", cost=27})
Card:new(Commander,Rebel,{name="Garm Bel Iblis",  front="http://i.imgur.com/fmlXop3.jpg", cost=25})
Card:new(Commander,Rebel,{name="General Cracken",  front="http://i.imgur.com/0NHwrEL.jpg", cost=26})
Card:new(Commander,Rebel,{name="General Dodonna",  front="http://i.imgur.com/MsS9AN8.jpg", cost=20})
Card:new(Commander,Rebel,{name="General Madine",  front="http://i.imgur.com/ePeK8Ok.jpg", cost=30})
Card:new(Commander,Rebel,{name="General Rieekan",  front="http://i.imgur.com/Q6pSiLj.jpg", cost=34})
Card:new(Commander,Rebel,{name="Kyrsta Agate",  front=ASSETS_ROOT.."cards/commanders/kyrsta_agate_v2_1.jpg", cost=25})
Card:new(Commander,Rebel,{name="Leia Organa",  front="http://i.imgur.com/Xsqh5f0.jpg", cost=28})
Card:new(Commander,Rebel,{name="Mon Mothma",  front="http://i.imgur.com/ZK3rQeb.jpg", cost=27})
Card:new(Commander,Rebel,{name="General Draven",  front=ASSETS_ROOT.."cards/commanders/general_draven_v2_1.jpg", cost=28})

Empire = {
    factions={"Empire"}
}
--imperial
Card:new(Commander,Empire,{name="Admiral Konstantine",  front="http://i.imgur.com/ONoTDBL.jpg", cost=23})
Card:new(Commander,Empire,{name="Admiral Motti",  front="http://i.imgur.com/rkMe17G.jpg", cost=24})
Card:new(Commander,Empire,{name="Admiral Ozzel",  front="http://i.imgur.com/v0nThwx.jpg", cost=20})
Card:new(Commander,Empire,{name="Admiral Piett",  front="http://i.imgur.com/2D3DgQS.jpg", cost=22})
Card:new(Commander,Empire,{name="Admiral Screed",  front="http://i.imgur.com/DUToctV.jpg", cost=26})
Card:new(Commander,Empire,{name="Admiral Sloane",  front="http://i.imgur.com/rzZtf8B.jpg", cost=24})
Card:new(Commander,Empire,{name="Darth Vader",  front="http://i.imgur.com/ysyfpEF.jpg", cost=36})
Card:new(Commander,Empire,{name="Emperor Palpatine",  front="http://i.imgur.com/KBY36Qs.jpg", cost=35})
Card:new(Commander,Empire,{name="General Romodi",  front=ASSETS_ROOT.."cards/commanders/general_romodi_v2_1.jpg", cost=28})
Card:new(Commander,Empire,{name="General Tagge",  front="http://i.imgur.com/LduHiR8.jpg", cost=25})
Card:new(Commander,Empire,{name="Grand Admiral Thrawn",  front="http://i.imgur.com/FSpE1gl.jpg", cost=32})
Card:new(Commander,Empire,{name="Grand Moff Tarkin",  front="http://i.imgur.com/OxvHWmA.jpg", cost=28})
Card:new(Commander,Empire,{name="Moff Jerjerrod",  front="http://i.imgur.com/qZAVH6a.jpg", cost=23})

Republic = {
    factions={"Republic"}
}
--republic
Card:new(Commander,Republic,{name="Bail Organa",  front="https://i.imgur.com/SBYa2yD.jpeg", cost=28})
Card:new(Commander,Republic,{name="Obi-Wan Kenobi",  front="https://i.imgur.com/xkfBnRw.jpeg", cost=28, aliases = {"Obi Wan Kenobi"}})
Card:new(Commander,Republic,{name="Luminara Unduli",  front="https://i.imgur.com/SlkHtHE.png", cost=25})
Card:new(Commander,Republic,{name="Admiral Tarkin",  front="https://i.imgur.com/mJplVe5.png", cost=30})
Card:new(Commander,Republic,{name="Admiral Yularen", front="https://i.imgur.com/QloblZJ.jpeg", cost=24})
Card:new(Commander,Republic,{name="Plo Koon", front="https://i.imgur.com/RY01HsT.jpg", cost=26})
Card:new(Commander,Republic,{name="Anakin Skywalker",  front=ASSETS_ROOT.."cards/commanders/anakin_skywalker_v2_1.jpg", cost=31})

Separatist = {
    factions={"Separatist"}
}
--separatist
Card:new(Commander,Separatist,{name="Count Dooku",  front="https://i.imgur.com/YOm4LIi.jpeg", cost=30})
Card:new(Commander,Separatist,{name="Kraken",  front="https://i.imgur.com/zLNsrOo.jpeg", cost=30})
Card:new(Commander,Separatist,{name="General Grievous",  front="https://i.imgur.com/xLHg92l.png", cost=20})
Card:new(Commander,Separatist,{name="Admiral Trench", front="https://i.imgur.com/eOaryOm.png", cost=36})
Card:new(Commander,Separatist,{name="Mar Tuuk", front="https://i.imgur.com/POTMBXQ.png", cost=28})
Card:new(Commander,Separatist,{name="TF-1726", front="https://i.imgur.com/aptrDok.png", cost=26})
