ExperimentalRetrofit = {
    type="ExperimentalRetrofit",
    back = "https://i.imgur.com/SAnzYjF.png"
}
Card:new(ExperimentalRetrofit,{name="G-8 Experimental Projector", front="https://i.imgur.com/DUzGkon.jpg", cost=8})
Card:new(ExperimentalRetrofit,{name="G7-X Grav Well Projector", front="https://i.imgur.com/BaMEJzl.jpg", cost=2})
Card:new(ExperimentalRetrofit,{name="Grav Shift Reroute", front="https://i.imgur.com/QipiGSD.jpg", cost=2})
Card:new(ExperimentalRetrofit,{name="Targeting Scrambler", front="https://i.imgur.com/KoUrM8N.jpg", cost=5})
