Ship:new(SmallShip,{
	name = "Hardcell-class Transport",
    front = "https://i.imgur.com/T7QWSb4.jpeg",
    back = "https://i.imgur.com/c9yNLyu.jpg",
    mesh = "http://paste.ee/r/XbByc",
    diffuse = "http://i.imgur.com/ALhJKGI.jpg",
    ruler = "http://paste.ee/r/NxRRi",
    maneuver = {{"II"},{"I","I"},{"I","I","-"}},
    defense_tokens = {DEF_EVADE,DEF_BRACE,DEF_REDIRECT},
    shields = {3,1,1,2},
    cost = 47
})
Ship:new(SmallShip,{
	name = "Hardcell-class Battle Refit",
    front = "https://i.imgur.com/X96bJDW.jpeg",
    back = "https://i.imgur.com/Q46N3zb.jpeg",
    mesh = "http://paste.ee/r/XbByc",
    diffuse = "http://i.imgur.com/KQiWyCh.jpeg",
    ruler = "http://paste.ee/r/NxRRi",
    maneuver = {{"II"},{"I","I"},{"I","I","-"}},
    defense_tokens = {DEF_EVADE,DEF_BRACE,DEF_REDIRECT},
    shields = {3,1,1,2},
    cost = 52
})

Ship:new(MediumShip,{
	name = "Munificent-class Comms Frigate",
    front = "https://i.imgur.com/T5LCaof.jpeg",
    back = "https://i.imgur.com/5BgxeQS.jpeg",
    mesh = "http://paste.ee/r/5vQzm",
    diffuse = "http://i.imgur.com/UHhtE2H.png",
    ruler = "http://paste.ee/r/wq1eM",
    maneuver = {{"I"},{"I","II"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_SALVO},
    shields = {4,3,3,2},
    cost = 70
})
Ship:new(MediumShip,{
	name = "Munificent-class Star Frigate",
    front = "https://i.imgur.com/kN6lJzW.jpeg",
    back = "https://i.imgur.com/8qP8mto.jpeg",
    mesh = "http://paste.ee/r/5vQzm",
    diffuse = "http://i.imgur.com/drGaSmk.jpg",
    ruler = "http://paste.ee/r/wq1eM",
    maneuver = {{"I"},{"I","II"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_SALVO},
    shields = {4,3,3,2},
    cost = 73
})
