EMPIRE_SHIP = {
    back = "https://i.imgur.com/Ag3p9fo.png",
    faction = "Empire"
}
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Gozanti-class Cruisers",
    front = "https://i.imgur.com/MBkIeoQ.png",
    mesh = "http://paste.ee/r/a4Qg8",
    diffuse = "http://i.imgur.com/98SoFSS.png",
    ruler = "http://paste.ee/r/jbTlM",
    maneuver = {{"II"},{"I","I"},{"I","I","-"}},
    defense_tokens = {DEF_SCATTER, DEF_EVADE},
    shields = {1,1,1,1},
    cost = 23,
    aliases = {"Gozanti Cruisers"},
    command = 1
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Gozanti-class Assault Carriers",
    front = "https://i.imgur.com/LMf2YI6.png",
    mesh = "http://paste.ee/r/a4Qg8",
    diffuse = "http://i.imgur.com/US2K0XY.png",
    ruler = "http://paste.ee/r/jbTlM",
    maneuver = {{"II"},{"I","I"},{"I","I","-"}},
    defense_tokens = {DEF_SCATTER, DEF_EVADE},
    shields = {1,1,1,1},
    cost = 28,
    aliases = {"Gozanti Assault Carriers"},
    command = 1
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Raider I-class Corvette",
    front = "https://i.imgur.com/C5LKczU.png",
    mesh = "http://paste.ee/r/qsGM3",
    diffuse = "http://i.imgur.com/uO4qw7R.png",
    ruler = "http://paste.ee/r/JwnWk",
    maneuver = {{"II"},{"II","II"},{"-","I","I"},{"-","I","I","I"}},
    defense_tokens = {DEF_EVADE,DEF_EVADE,DEF_BRACE},
    shields = {2,2,2,2},
    cost = 44,
    aliases = {"Raider I","Raider I Corvette"},
    command = 1
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Raider II-class Corvette",
    front = "https://i.imgur.com/10Tytpi.png",
    mesh = "http://paste.ee/r/qsGM3",
    diffuse = "http://i.imgur.com/9uZDh0o.png",
    ruler = "http://paste.ee/r/JwnWk",
    maneuver = {{"II"},{"II","II"},{"-","I","I"},{"-","I","I","I"}},
    defense_tokens = {DEF_EVADE,DEF_EVADE,DEF_BRACE},
    shields = {2,2,2,2},
    cost = 48,
    aliases = {"Raider II","Raider II Corvette"},
    command = 1
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Gladiator I-class Star Destroyer",
    front = "https://i.imgur.com/SqGqZD2.png",
    mesh = "http://paste.ee/r/2IdyR",
    diffuse = "http://i.imgur.com/XWOtLVv.jpg",
    ruler = "http://paste.ee/r/PnVAt",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_EVADE,DEF_BRACE,DEF_REDIRECT},
    shields = {3,2,2,1},
    cost = 56,
    aliases = {"Gladiator I","Gladiator I Star Destroyer"},
    command = 2
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Gladiator II-class Star Destroyer",
    front = "https://i.imgur.com/UkX25YU.png",
    mesh = "http://paste.ee/r/2IdyR",
    diffuse = "http://i.imgur.com/XAMg2ke.jpg",
    ruler = "http://paste.ee/r/PnVAt",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_EVADE,DEF_BRACE,DEF_REDIRECT},
    shields = {3,2,2,1},
    cost = 62,
    aliases = {"Gladiator II","Gladiator II Star Destroyer"},
    command = 2
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Arquitens-class Light Cruiser",
    front = "https://i.imgur.com/cRimUl0.png",
    mesh = "http://paste.ee/p/i5otm",
    diffuse = "http://i.imgur.com/QAy7MNw.png",
    ruler = "http://paste.ee/p/wZK5w",
    maneuver = {{"II"},{"-","II"},{"-","-","II"}},
    defense_tokens = {DEF_EVADE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {2,2,2,2},
    cost = 54,
    aliases = {"Arquitens Light Cruiser"},
    command = 2
})
Ship:new(SmallShip,EMPIRE_SHIP,{
	name = "Arquitens-class Command Cruiser",
    front = "https://i.imgur.com/gMUjnfM.png",
    mesh = "http://paste.ee/p/i5otm",
    diffuse = "http://i.imgur.com/yxQ3F2V.png",
    ruler = "http://paste.ee/p/wZK5w",
    maneuver = {{"II"},{"-","II"},{"-","-","II"}},
    defense_tokens = {DEF_EVADE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {2,2,2,2},
    cost = 59,
    aliases = {"Arquitens Command Cruiser"},
    command = 2
    --maneuver = "II|-,II|-,-,II"
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Victory I-class Star Destroyer",
    front = "https://i.imgur.com/qcN5LEl.png",
    mesh = "http://paste.ee/r/pPCJ8",
    diffuse = "http://i.imgur.com/b7CDloK.png",
    ruler = "http://paste.ee/r/f1IHk",
    maneuver = {{"I"},{"-","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT},
    shields = {3,3,3,1},
    cost = 73,
    aliases = {"Victory I Star Destroyer","Victory I", "VSD I", "VSD 1"},
    command = 3
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Victory II-class Star Destroyer",
    front = "https://i.imgur.com/W8kLKpj.png",
    mesh = "http://paste.ee/r/pPCJ8",
    diffuse = "http://i.imgur.com/BB2Rflo.png",
    ruler = "http://paste.ee/r/f1IHk",
    maneuver = {{"I"},{"-","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT},
    shields = {3,3,3,1},
    cost = 85,
    aliases = {"Victory II Star Destroyer","Victory II", "VSD II", "VSD 2"},
    command = 3
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Interdictor Suppression Refit",
    front = "https://i.imgur.com/kB3R9ds.png",
    mesh = "http://paste.ee/r/roSj5",
    diffuse = "http://i.imgur.com/OMoTh9y.png",
    ruler = "http://paste.ee/r/cqUDP",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {3,2,2,2},
    cost = 90,
    aliases = {"Interdictor-class Suppression Refit"},
    command = 2
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Interdictor Combat Refit",
    front = "https://i.imgur.com/lMiL8Df.png",
    mesh = "http://paste.ee/r/roSj5",
    diffuse = "http://i.imgur.com/0xIlJlb.png",
    ruler = "http://paste.ee/r/cqUDP",
    maneuver = {{"I"},{"I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {3,2,2,2},
    cost = 93,
    aliases = {"Interdictor-class Combat Refit"},
    command = 2
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Quasar Fire I-class Cruiser-Carrier",
    front = "https://i.imgur.com/7XMsdsM.png",
    mesh = "http://paste.ee/p/aoLPn",
    diffuse = "http://i.imgur.com/WyRNlCF.png",
    ruler = "http://paste.ee/p/wOQfL",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT},
    shields = {2,2,2,1},
    cost = 54,
    aliases = {"Quasar Fire I Cruiser-Carrier","Quasar Fire I", "Quasar I"},
    command = 2
})
Ship:new(MediumShip,EMPIRE_SHIP,{
	name = "Quasar Fire II-class Cruiser-Carrier",
    front = "https://i.imgur.com/lO6OBYS.png",
    mesh = "http://paste.ee/p/aoLPn",
    diffuse = "http://i.imgur.com/xfMXMUr.png",
    ruler = "http://paste.ee/p/wOQfL",
    maneuver = {{"II"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT},
    shields = {2,2,2,1},
    cost = 61,
    aliases = {"Quasar Fire II Cruiser-Carrier","Quasar Fire II", "Quasar II"},
    command = 2
})

Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Imperial I-class Star Destroyer",
    front = "https://i.imgur.com/Gg2bqJM.png",
    mesh = "http://paste.ee/r/jrPtR",
    diffuse = "http://i.imgur.com/FrFBut6.png",
    ruler = "http://paste.ee/r/6SQoL",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {4,3,3,2},
    cost = 110,
    aliases = {"Imperial I Star Destroyer","Imperial I", "ISD I", "ISD 1"},
    command = 3
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Imperial Star Destroyer Kuat Refit",
    front = "https://i.imgur.com/443vU9i.png",
    mesh = "http://paste.ee/r/jrPtR",
    diffuse = "http://i.imgur.com/qoeLpbp.png",
    ruler = "http://paste.ee/r/6SQoL",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {4,3,3,2},
    cost = 112,
    aliases = {"Imperial Kuat Refit","Kuat Refit", "ISD Kuat Refit"},
    command = 3
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Imperial II-class Star Destroyer",
    front = "https://i.imgur.com/wCgFDmm.png",
    mesh = "http://paste.ee/r/jrPtR",
    diffuse = "http://i.imgur.com/usykAgi.png",
    ruler = "http://paste.ee/r/6SQoL",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {4,3,3,2},
    cost = 120,
    aliases = {"Imperial II Star Destroyer","Imperial II", "ISD II", "ISD 2"},
    command = 3
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Imperial Star Destroyer Cymoon 1 Refit",
    front = "https://i.imgur.com/6hVaf98.png",
    mesh = "http://paste.ee/r/jrPtR",
    diffuse = "http://i.imgur.com/vzypdB4.png",
    ruler = "http://paste.ee/r/6SQoL",
    maneuver = {{"I"},{"I","I"},{"-","I","I"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN},
    shields = {4,3,3,2},
    cost = 112,
    aliases = {"Imperial Cymoon 1 Refit","Cymoon 1 Refit", "ISD Cymoon 1 Refit", "ISD Cymoon"},
    command = 3
})

Ship:new(HugeShip,EMPIRE_SHIP,{
	name = "Star Dreadnought Command Prototype",
    front = "https://i.imgur.com/5oilBpo.png",
    mesh = "http://paste.ee/r/aDtaX",
    diffuse = "http://i.imgur.com/nlC3Pj6.jpg",
    ruler = "http://paste.ee/p/xLzvA",
    maneuver = {{"-"},{"-","-"}},
    defense_tokens = {DEF_BRACE,DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {6,3,3,2,3,3},
    cost = 220,
    aliases = {"SSD Command Prototype","Command Prototype"},
    command = 4,
    hull = 22
})
Ship:new(HugeShip,EMPIRE_SHIP,{
	name = "Star Dreadnought Assault Prototype",
    front = "https://i.imgur.com/QhAu7ta.png",
    mesh = "http://paste.ee/r/aDtaX",
    diffuse = "http://i.imgur.com/04lWufJ.jpg",
    ruler = "http://paste.ee/p/xLzvA",
    maneuver = {{"-"},{"-","-"}},
    defense_tokens = {DEF_BRACE,DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {6,3,3,2,3,3},
    cost = 250,
    aliases = {"SSD Assault Prototype","Assault Prototype"},
    command = 4,
    hull = 22
})
Ship:new(HugeShip,EMPIRE_SHIP,{
	name = "Executor I-class Star Dreadnought",
    front = "https://i.imgur.com/HQwM67x.png",
    mesh = "http://paste.ee/r/aDtaX",
    diffuse = "http://i.imgur.com/EmhgOtb.jpg",
    ruler = "http://paste.ee/p/xLzvA",
    maneuver = {{"-"},{"-","-"}},
    defense_tokens = {DEF_BRACE,DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {6,5,5,3,5,5},
    cost = 381,
    aliases = {"Executor I Star Dreadnought", "Executor I SSD","Executor I"},
    command = 4,
    hull = 33
})
Ship:new(HugeShip,EMPIRE_SHIP,{
	name = "Executor II-class Star Dreadnought",
    front = "https://i.imgur.com/X0PsSTN.png",
    mesh = "http://paste.ee/r/aDtaX",
    diffuse = "http://i.imgur.com/t6e3YRH.jpg",
    ruler = "http://paste.ee/p/xLzvA",
    maneuver = {{"-"},{"-","-"}},
    defense_tokens = {DEF_BRACE,DEF_BRACE,DEF_REDIRECT,DEF_REDIRECT,DEF_CONTAIN,DEF_CONTAIN},
    shields = {6,5,5,3,5,5},
    cost = 411,
    aliases = {"Executor II Star Dreadnought", "Executor II SSD","Executor II"},
    command = 4,
    hull = 33
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Onager-class Testbed",
    front = "https://i.imgur.com/EAv7Koo.png",
    mesh = "http://paste.ee/p/Ul9r9",
    diffuse = "http://i.imgur.com/4KJskDx.jpg",
    ruler = "http://paste.ee/p/OS2w9",
    maneuver = {{"I"},{"I","I"},{"I","I",'-'}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_SALVO},
    shields = {5,2,2,1},
    cost = 96,
    aliases = {"Onager Testbed"},
    command = 3
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Onager-class Star Destroyer",
    front = "https://i.imgur.com/eqHrxL7.png",
    mesh = "http://paste.ee/p/Ul9r9",
    diffuse = "http://i.imgur.com/xbMdMb0.jpg",
    ruler = "http://paste.ee/p/OS2w9",
    maneuver = {{"I"},{"I","I"},{"I","I",'-'}},
    defense_tokens = {DEF_BRACE, DEF_REDIRECT, DEF_SALVO},
    shields = {5,2,2,1},
    cost = 110,
    aliases = {"Onager Star Destroyer"},
    command = 3
})
Ship:new(LargeShip,EMPIRE_SHIP,{
	name = "Venator II-class Star Destroyer (imp)",
    front = "https://i.imgur.com/apXXabO.png",
    back = "https://i.imgur.com/Q9Vdi1p.png",
    mesh = "https://paste.ee/r/IuqFO",
    diffuse = "https://i.imgur.com/LChyZuT.png",
    ruler = "http://paste.ee/r/xTAdu",
    maneuver = {{"I"},{"I","I"},{"-","I","-"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_CONTAIN,DEF_SALVO},
    shields = {4,3,3,2},
    cost = 100,
	aliases = {"Venator II Star Destroyer (imp)", "Venator II (imp)"},
    command = 3
})
