EMPIRE_SQUAD = {
    back = "https://i.imgur.com/8KAyFCq.png",
    faction = "Empire"
}
ship = {
    mesh = "http://paste.ee/p/Foax6",
    diffuse = "http://i.imgur.com/iuWpy6O.png",
    health = 3,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "TIE Fighter Squadron",
    front = "https://i.imgur.com/IBPIZFC.png",
    cost = 8,
    aliases = {"TIE Fighter Squadrons", "TIE Fighter"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = '"Mauler" Mithel',
    front = "https://i.imgur.com/XOrV29v.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 15,
    aliases = {"Mauler Mithel"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = '"Howlrunner"',
    front = "https://i.imgur.com/9JyPCY1.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 16,
    aliases = {"Howlrunner"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Valen Rudor',
    front = "https://i.imgur.com/jJbbq5p.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 13
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Black Squadron',
    front = "https://i.imgur.com/wHVRghK.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    mesh = "http://paste.ee/p/3kuIp",
    cost = 9
})
ship = {
    mesh = "http://paste.ee/r/tSt9Z",
    diffuse = "http://i.imgur.com/eonWxFU.png",
    health = 3,
    move = 5,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "TIE Interceptor Squadron",
    front = "https://i.imgur.com/sEjCnbR.png",
    cost = 11,
    aliases = {"TIE Interceptor Squadrons", "TIE Interceptor"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Soontir Fel",
    front = "https://i.imgur.com/OFz3wPf.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 18
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Ciena Ree",
    front = "https://i.imgur.com/gGsK5NT.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 17
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Saber Squadron",
    front = "https://i.imgur.com/xjsjQjV.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    mesh = "http://paste.ee/p/GqMPV",
    cost = 12
})
ship = {
    mesh = "http://paste.ee/r/QPs1M",
    diffuse = "http://i.imgur.com/L6U7Pca.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "TIE Bomber Squadron",
    front = "https://i.imgur.com/JGg79So.png",
    cost = 9,
    aliases = {"TIE Bomber Squadrons", "TIE Bomber"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Major Rhymer",
    front = "https://i.imgur.com/fPUE6qa.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 16
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Captain Jonus",
    front = "https://i.imgur.com/iNHpN8D.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    mesh = "http://paste.ee/p/ekNwl",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 16
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Gamma Squadron",
    front = "https://i.imgur.com/MuOU5H0.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    mesh = "http://paste.ee/p/cFgCe",
    cost = 10
})
ship = {
    mesh = "http://paste.ee/r/5YfqM",
    diffuse = "http://i.imgur.com/VDIMZqW.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "TIE Advanced Squadron",
    front = "https://i.imgur.com/oqevOIs.png",
    cost = 12,
    aliases = {"TIE Advanced Squadrons", "TIE Advanced"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Darth Vader",
    front = "https://i.imgur.com/qMTERFQ.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 21
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Zertik Strom",
    front = "https://i.imgur.com/92y5pLs.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 15
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Tempest Squadron",
    front = "https://i.imgur.com/Pco10DS.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    mesh = "http://paste.ee/p/6Zar9",
    cost = 13
})
ship = {
    mesh = "http://paste.ee/r/SsZzy",
    diffuse = "http://i.imgur.com/xq6IPfk.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Firespray-31",
    front = "https://i.imgur.com/dmC3jNm.png",
    cost = 18,
    aliases = {"Firespray-31s"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Boba Fett",
    front = "https://i.imgur.com/SwdbJdL.png",
    diffuse = "http://i.imgur.com/rH8e7j0.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 26
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Hondo Ohnaka",
    front = "https://i.imgur.com/K8A1QGa.png",
    mesh = "http://paste.ee/p/2zmZV",
    diffuse = "http://i.imgur.com/rH8e7j0.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 24
})
ship = {
    mesh = "http://paste.ee/r/6kd8r",
    diffuse = "http://i.imgur.com/iEZieyE.png",
    health = 4,
    move = 4 }
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "JumpMaster 5000",
    front = "https://i.imgur.com/pBix7LS.png",
    cost = 12,
    aliases = {"JumpMaster 5000s"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Dengar",
    front = "https://i.imgur.com/SGHkuVm.png",
    diffuse = "http://i.imgur.com/Y9MYLmc.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 20
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Tel Trevura",
    front = "https://i.imgur.com/8UTq2I7.png",
    mesh = "http://paste.ee/p/kpFas",
    diffuse = "http://i.imgur.com/Y9MYLmc.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 17
})
ship = {
    mesh = "http://paste.ee/r/Kc5iy",
    diffuse = "http://i.imgur.com/FW8XU1X.png",
    health = 5,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Aggressor Assault Fighter",
    front = "https://i.imgur.com/awIbXGE.png",
    cost = 16,
    aliases = {"Aggressor Assault Fighters"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "IG-88",
    front = "https://i.imgur.com/s9mWI5Z.png",
    diffuse = "http://i.imgur.com/eLOTz1a.png",
    move = 5,
    defense_tokens = {DEF_SCATTER},
    cost = 21
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "IG-88B",
    front = "https://i.imgur.com/yxjuseo.png",
    diffuse = "http://i.imgur.com/eLOTz1a.png",
    move = 5,
    defense_tokens = {DEF_SCATTER},
    cost = 21
})
ship = {
    mesh = "http://paste.ee/r/zRpzx",
    diffuse = "http://i.imgur.com/YU9FikV.png",
    health = 7,
    move = 2,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "YV-666",
    front = "https://i.imgur.com/VwtnRPG.png",
    cost = 15,
    aliases = {"YV-666s"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Bossk",
    front = "https://i.imgur.com/cO69PsD.png",
    mesh = "http://paste.ee/r/BX64Q",
    diffuse = "http://i.imgur.com/qGvYpdJ.png",
    move = 3,
    defense_tokens = {DEF_BRACE},
    cost = 23
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = "Moralo Eval",
    front = "https://i.imgur.com/Ylo65oA.png",
    mesh = "http://paste.ee/r/BX64Q",
    diffuse = "http://i.imgur.com/qGvYpdJ.png",
    move = 3,
    defense_tokens = {DEF_BRACE},
    cost = 22
})
ship = {
    mesh = "http://paste.ee/p/VogTD",
    diffuse = "http://i.imgur.com/lJBVPTD.png",
    health = 4,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'TIE Phantom Squadron',
    front = "https://i.imgur.com/Tvy7ZfX.png",
    cost = 14,
    aliases = {"TIE Phantom Squadrons", "TIE Phantom"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = '"Whisper"',
    front = "https://i.imgur.com/vsrwlnW.png",
    diffuse = "http://i.imgur.com/wKQfGQs.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER},
    cost = 20,
    aliases = {"Whisper"}
})
ship = {
    mesh = "http://paste.ee/p/4Nnjz",
    diffuse = "http://i.imgur.com/pXxfv23.png",
    health = 6,
    move = 5,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'TIE Defender Squadron',
    front = "https://i.imgur.com/h5OJeUV.png",
    cost = 16,
    aliases = {"TIE Defender Squadrons", "TIE Defender"}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Maarek Stele',
    front = "https://i.imgur.com/iVPlLtU.png",
    mesh = "http://paste.ee/p/hQtGH",
    diffuse = "http://i.imgur.com/2wkGtqX.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 21
})
ship = {
    mesh = "http://paste.ee/p/EriDZ",
    diffuse = "http://i.imgur.com/VE1qnP0.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Lambda-class Shuttle',
    front = "https://i.imgur.com/8q9RtT0.png",
    cost = 15,
    aliases = {'Lambda Shuttle', 'Lambda Shuttles', 'Lambda-class Shuttles'}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Colonel Jendon',
    front = "https://i.imgur.com/D5vKvP1.png",
    mesh = "http://paste.ee/p/LJqy6",
    diffuse = "http://i.imgur.com/ku8uSvD.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
    cost = 20
})
ship = {
    mesh = "http://paste.ee/p/2k8Qn",
    diffuse = "http://i.imgur.com/YQ501vt.png",
    health = 8,
    move = 3,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'VT-49 Decimator',
    front = "https://i.imgur.com/Vpztyfk.png",
    cost = 22,
    aliases = {'VT-49 Decimators'}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Morna Kee',
    front = "https://i.imgur.com/w8nzg3K.png",
    mesh = "http://paste.ee/p/5DPYJ",
    diffuse = "http://i.imgur.com/JHZ5Ig0.png",
    defense_tokens = {DEF_BRACE},
    cost = 27
})
ship = {
    mesh = "http://paste.ee/p/T3Fo3",
    diffuse = "http://i.imgur.com/e7D6q10.png",
    health = 7,
    move = 4,
    defense_tokens = {}}
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Mandalorian Gauntlet Fighter',
    front = "https://i.imgur.com/EojO5GT.png",
    cost = 20,
    aliases = {'Mandalorian Gauntlet Fighters'}
})
Squadron:new(ship, EMPIRE_SQUAD, {
	name = 'Gar Saxon',
    front = "https://i.imgur.com/cj1OidE.png",
    diffuse = "http://i.imgur.com/WjuhLC8.png",
    defense_tokens = {DEF_BRACE},
    cost = 23
})
