EMPIRE_SQUAD = {
    back = "https://i.imgur.com/8KAyFCq.png"
}
ship = {
    mesh = "http://paste.ee/p/Foax6",
    diffuse = "http://i.imgur.com/iuWpy6O.png",
    health = 3,
    move = 4,
    defense_tokens = {}}
SHIPS["TIE Fighter Squadron"] = Squadron:new(ship,empire, {
    front = "https://i.imgur.com/IBPIZFC.png"
})
SHIPS['"Mauler" Mithel'] = Squadron:new(ship,empire, {
    front = "https://i.imgur.com/XOrV29v.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS['"Howlrunner"'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/9JyPCY1.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS['Valen Rudor'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/jJbbq5p.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS['Black Squadron'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/wHVRghK.png",
    diffuse = "http://i.imgur.com/aKtLAbl.png",
    mesh = "http://paste.ee/p/3kuIp"
})
ship = {
    mesh = "http://paste.ee/r/tSt9Z",
    diffuse = "http://i.imgur.com/eonWxFU.png",
    health = 3,
    move = 5,
    defense_tokens = {}}
SHIPS["TIE Interceptor Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/sEjCnbR.png"
})
SHIPS["Soontir Fel"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/OFz3wPf.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS["Ciena Ree"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/gGsK5NT.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS["Saber Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/xjsjQjV.png",
    diffuse = "http://i.imgur.com/19ksb4d.png",
    mesh = "http://paste.ee/p/GqMPV"
})
ship = {
    mesh = "http://paste.ee/r/QPs1M",
    diffuse = "http://i.imgur.com/L6U7Pca.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
SHIPS["TIE Bomber Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/JGg79So.png"
})
SHIPS["Major Rhymer"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/fPUE6qa.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Captain Jonus"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/iNHpN8D.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    mesh = "http://paste.ee/p/ekNwl",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Gamma Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/MuOU5H0.png",
    diffuse = "http://i.imgur.com/o9KJLV8.png",
    mesh = "http://paste.ee/p/cFgCe"
})
ship = {
    mesh = "http://paste.ee/r/5YfqM",
    diffuse = "http://i.imgur.com/VDIMZqW.png",
    health = 5,
    move = 4,
    defense_tokens = {}}
SHIPS["TIE Advanced Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/oqevOIs.png"
})
SHIPS["Darth Vader"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/qMTERFQ.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE},
})
SHIPS["Zertik Strom"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/92y5pLs.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Tempest Squadron"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/Pco10DS.png",
    diffuse = "http://i.imgur.com/YJm6aoS.png",
    mesh = "http://paste.ee/p/6Zar9"
})
ship = {
    mesh = "http://paste.ee/r/SsZzy",
    diffuse = "http://i.imgur.com/xq6IPfk.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
SHIPS["Firespray-31"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/dmC3jNm.png"
})
SHIPS["Boba Fett"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/SwdbJdL.png",
    diffuse = "http://i.imgur.com/rH8e7j0.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
SHIPS["Hondo Ohnaka"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/K8A1QGa.png",
    mesh = "http://paste.ee/p/2zmZV",
    diffuse = "http://i.imgur.com/rH8e7j0.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/r/6kd8r",
    diffuse = "http://i.imgur.com/iEZieyE.png",
    health = 4,
    move = 4 }
SHIPS["JumpMaster 5000"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/pBix7LS.png"
})
SHIPS["Dengar"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/SGHkuVm.png",
    diffuse = "http://i.imgur.com/Y9MYLmc.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
SHIPS["Tel Trevura"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/8UTq2I7.png",
    mesh = "http://paste.ee/p/kpFas",
    diffuse = "http://i.imgur.com/Y9MYLmc.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
ship = {
    mesh = "http://paste.ee/r/Kc5iy",
    diffuse = "http://i.imgur.com/FW8XU1X.png",
    health = 5,
    move = 3,
    defense_tokens = {}}
SHIPS["Aggressor Assault Fighter"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/awIbXGE.png"
})
SHIPS["IG-88"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/s9mWI5Z.png",
    diffuse = "http://i.imgur.com/eLOTz1a.png",
    move = 5,
    defense_tokens = {DEF_SCATTER}
})
SHIPS["IG-88B"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/yxjuseo.png",
    diffuse = "http://i.imgur.com/eLOTz1a.png",
    move = 5,
    defense_tokens = {DEF_SCATTER}
})
ship = {
    mesh = "http://paste.ee/r/zRpzx",
    diffuse = "http://i.imgur.com/YU9FikV.png",
    health = 7,
    move = 2,
    defense_tokens = {}}
SHIPS["YV-666"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/VwtnRPG.png"
})
SHIPS["Bossk"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/cO69PsD.png",
    mesh = "http://paste.ee/r/BX64Q",
    diffuse = "http://i.imgur.com/qGvYpdJ.png",
    move = 3,
    defense_tokens = {DEF_BRACE}
})
SHIPS["Moralo Eval"] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/Ylo65oA.png",
    mesh = "http://paste.ee/r/BX64Q",
    diffuse = "http://i.imgur.com/qGvYpdJ.png",
    move = 3,
    defense_tokens = {DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/VogTD",
    diffuse = "http://i.imgur.com/lJBVPTD.png",
    health = 4,
    move = 4,
    defense_tokens = {}}
SHIPS['TIE Phantom Squadron'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/Tvy7ZfX.png"
})
SHIPS['"Whisper"'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/vsrwlnW.png",
    diffuse = "http://i.imgur.com/wKQfGQs.png",
    defense_tokens = {DEF_BRACE,DEF_SCATTER}
})
ship = {
    mesh = "http://paste.ee/p/4Nnjz",
    diffuse = "http://i.imgur.com/pXxfv23.png",
    health = 6,
    move = 5,
    defense_tokens = {}}
SHIPS['TIE Defender Squadron'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/h5OJeUV.png"
})
SHIPS['Maarek Stele'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/iVPlLtU.png",
    mesh = "http://paste.ee/p/hQtGH",
    diffuse = "http://i.imgur.com/2wkGtqX.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/EriDZ",
    diffuse = "http://i.imgur.com/VE1qnP0.png",
    health = 6,
    move = 3,
    defense_tokens = {}}
SHIPS['Lambda-class Shuttle'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/8q9RtT0.png"
})
SHIPS['Colonel Jendon'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/D5vKvP1.png",
    mesh = "http://paste.ee/p/LJqy6",
    diffuse = "http://i.imgur.com/ku8uSvD.png",
    defense_tokens = {DEF_BRACE,DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/2k8Qn",
    diffuse = "http://i.imgur.com/YQ501vt.png",
    health = 8,
    move = 3,
    defense_tokens = {}}
SHIPS['VT-49 Decimator'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/Vpztyfk.png"
})
SHIPS['Morna Kee'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/w8nzg3K.png",
    mesh = "http://paste.ee/p/5DPYJ",
    diffuse = "http://i.imgur.com/JHZ5Ig0.png",
    defense_tokens = {DEF_BRACE}
})
ship = {
    mesh = "http://paste.ee/p/T3Fo3",
    diffuse = "http://i.imgur.com/e7D6q10.png",
    health = 7,
    move = 4,
    defense_tokens = {}}
SHIPS['Mandalorian Gauntlet Fighter'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/EojO5GT.png"
})
SHIPS['Gar Saxon'] = Squadron:new(ship, EMPIRE_SQUAD, {
    front = "https://i.imgur.com/cj1OidE.png",
    diffuse = "http://i.imgur.com/WjuhLC8.png",
    defense_tokens = {DEF_BRACE}
})
