REPUBLIC_SHIP = {
    faction = "Republic"
}

Ship:new(SmallShip,REPUBLIC_SHIP,{
	name = "Consular-class Armed Cruiser",
    front = "https://i.imgur.com/CV9k4Fz.jpeg",
    back = "https://i.imgur.com/nzWUP25.jpg",
    mesh = "http://paste.ee/r/EVWCx",
    diffuse = "http://i.imgur.com/qNEdxDn.jpg",
    ruler = "http://paste.ee/r/i9SWj",
    maneuver = {{"II"},{"II","I"},{"I","I","I"},{"I","-","I","I"}},
    defense_tokens = {DEF_EVADE, DEF_REDIRECT, DEF_CONTAIN},
    shields = {2,2,2,1},
    cost = 37,
	aliases = {"Consular Armed Cruiser","Armed Cruiser"},
    command = 1
})
Ship:new(SmallShip,REPUBLIC_SHIP,{
	name = "Consular-class Charger c70",
    front = "https://i.imgur.com/CXHwzPR.jpeg",
    back = "https://i.imgur.com/vpvKfAO.jpeg",
    mesh = "http://paste.ee/r/EVWCx",
    diffuse = "http://i.imgur.com/SbZMyrq.jpg",
    ruler = "http://paste.ee/r/i9SWj",
    maneuver = {{"II"},{"II","I"},{"I","I","I"},{"I","-","I","I"}},
    defense_tokens = {DEF_EVADE, DEF_REDIRECT, DEF_CONTAIN},
    shields = {2,2,2,1},
    cost = 45,
	aliases = {"Consular Charger c70","Charger c70"},
    command = 1
})

Ship:new(MediumShip,REPUBLIC_SHIP,{
	name = "Acclamator I-class Assault Ship",
    front = "https://i.imgur.com/6JbZwXG.jpeg",
    back = "https://i.imgur.com/T9fOJEE.jpg",
    mesh = "http://paste.ee/r/TUCP2",
    diffuse = "http://i.imgur.com/0MglVoM.jpg",
    ruler = "http://paste.ee/r/r0umF",
    maneuver = {{"I"},{"I","-"},{"-","I","-"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_SALVO},
    shields = {4,2,2,2},
    cost = 66,
	aliases = {"Acclamator I Assault Ship", "Acclamator I"},
    command = 3
})
Ship:new(MediumShip,REPUBLIC_SHIP,{
	name = "Acclamator II-class Assault Ship",
    front = "https://i.imgur.com/NhED6cA.jpg",
    back = "https://i.imgur.com/IpDPpzX.jpeg",
    mesh = "http://paste.ee/r/TUCP2",
    diffuse = "http://i.imgur.com/wfn0n32.jpg",
    ruler = "http://paste.ee/r/r0umF",
    maneuver = {{"I"},{"I","-"},{"-","I","-"}},
    defense_tokens = {DEF_BRACE,DEF_REDIRECT,DEF_SALVO},
    shields = {4,2,2,2},
    cost = 71,
	aliases = {"Acclamator II Assault Ship", "Acclamator II"},
    command = 3
})
