
local AI_DEFS = {}
local campaigns = {'HOTAC','PALLAS','DOTE','MISC'}
local REBELLION = "Rebellion"
local EMPIRE = "Empire"
local SCUM = "Scum"
local FACTIONS = {REBELLION, EMPIRE, SCUM}
local SHIP_TYPES = {}
-- TODO: Meshes for other spawning
-- MESH= {
--     GR = 'https://paste.ee/r/h5ND1',
--     YT = 'https://paste.ee/r/kkPoB'
-- }
-- DIFFUSE = {
--     GR = 'http://i.imgur.com/Nur18O2.jpg',
--     YT = 'http://i.imgur.com/QiomPcM.jpg'
-- }
-- COLLIDER = {
--     GR = 'https://paste.ee/r/qIaBu',
--     YT = 'https://paste.ee/r/LIxnJ'
-- }

local squad_types_deck = {}
local pilot_card_offsets = {} --{TIE=0,INT=1,BOM=7,ADV=13, DEF=17, PHA=21, SHU=25 }
local pilot_card_num = {} --{TIE=1,INT=6,BOM=6,ADV=4,DEF=4,PHA=4,SHU=4}
-- function getAI_DEFS()
--     return AI_DEFS[campaign]
-- end
function initialize_ai()
    for _,campaign in ipairs(campaigns) do
	    AI_DEFS[campaign] = {}
        pilot_card_offsets[campaign] = {}
        pilot_card_num[campaign] = {}
        squad_types_deck[campaign] = {}
    end
	-- AI_DEFS['HOTAC'] = {}
	-- AI_DEFS['PALLAS'] = {}
	-- AI_DEFS['DOTE'] = {}
	HostileAiDefinition = {
        faction = '',
        shipType = '',
        description = '',
	    isHostile = true,
	    isLargeShip = false,
        ignoresHugeShips = false,
	    mesh = '',
	    diffuse = '',
	    collider = '',
	    typeColor = 'FFFFFF',
	    has360Turret = false,
	    hasCloak = false,
	    hasFreeFocus = false,
	    hasFreeEvade = false,
	    hasFreeTargetLock = false,
	    hasFreeBarrelRoll = false,
	    hasBoost = false,
	    hasBarrelRoll = false,
	    hasConditionalFocus = true,
	    hasConditionalEvade = false,
	    hasConditionalTargetLock = false,
	    hasConditionalCloak = false,
        hasConditionalSlam = false, --TODO: IMPLEMENT
	    elitePilotSkills = {},
	    elitePilotSkillDeckEntries = 0,
        pilotCards = {},
        elitePilotCards = {},
        alternate = nil,
        alternateLevel = nil,
        maneuverCard = '',
	    closeMoves = {},
	    farMoves = {},
        leftAlts = {},
	    fleeMoves = {},
	    swerves = {},
        eliteLimits = {4,6,8}
	}
	FriendlyAiDefinition = table.ShallowCopy(HostileAiDefinition)
	FriendlyAiDefinition.isHostile = false
	FriendlyAiDefinition.fleeHealth = 2
	FriendlyAiDefinition.hyperdriveMoves = {}
	function HostileAiDefinition:new(o)
	    o = o or {}
	    setmetatable(o, HostileAiDefinition)
	    HostileAiDefinition.__index = HostileAiDefinition
	    return o
	end
	function FriendlyAiDefinition:new(o)
	    o = o or {}
	    setmetatable(o, FriendlyAiDefinition)
	    FriendlyAiDefinition.__index = FriendlyAiDefinition
	    return o
	end
    AI_DEFS['HOTAC']['TIE'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Fighter',
        description = 'Academy Pilot',
        ignoresHugeShips = true,
        mesh = 'https://paste.ee/r/Yz0kt',
        diffuse = 'http://i.imgur.com/otxKcUx.png',
        collider = 'https://paste.ee/r/1dx1C',
        typeColor = '395567',
        hasBarrelRoll = true,
        hasConditionalEvade = true,
        elitePilotSkills = {1, nil, nil, nil, nil},
        elitePilotSkillDeckEntries = 1,
        pilotCards = {'https://i.imgur.com/zwDeJE8.png'},
        maneuverCard = 'https://i.imgur.com/XBEruHe.jpg',
        closeMoves = {{'bl2','br2','s2','s2','k4*','k4*'},
                      {'s2','br2','br2','k4*','k4*','tr1'},
                      {'tr1','tr1','tr2','tr2','k3*','k4*'},
                      {'tr1','tr1','tr2','k3*','k4*','k4*'},
                      {'k4*','k3*','k3*','tl3','tr3','s5'}},
        farMoves =   {{'s5','s5','s5','s4','s4','s3'},
                      {'s3','br2','br3','br3','br3','tr3' },
                      {'br3','tr3','br2','tr2','tr2','tr1'},
                      {'k4*','k3*','k3*','tr2','tr2','tr1'},
                      {'k3*','k3*','k3*','k3*','tl1','tr1'}},
        fleeMoves =  {['tl1']='tl3', ['tl2']='tl3',
                      ['bl2']='bl3',
                      ['s2']='s5',['s3']='s5',['s4']='s5',
                      ['br2']='br3',
                      ['tr1']='tr3',['tr2']='tr3',
                      ['k4*']='k3*'},
        swerves =    {['tl1'] = {nil,'bl2'}, ['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                      ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                      ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'}, ['s5'] = {'bl3','br3'},
                      ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                      ['tr1'] = {'br2',nil },  ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                      ['k3*'] = {'bl3','br3'}, ['k4*'] = {'bl3','br3' } }
    }
    AI_DEFS['PALLAS']['TIE'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['HOTAC']['TIE']))
    AI_DEFS['PALLAS']['TIEE'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['HOTAC']['TIE']))
    AI_DEFS['PALLAS']['TIEE'].description = "Black Squadron Pilot" --"Obsidian Squadron Pilot" --TODO: Obsidian actually is PS3
    AI_DEFS['PALLAS']['TIEE'].elitePilotSkills = {2,4,5,7,9}
    AI_DEFS['PALLAS']['TIEE'].elitePilotSkillDeckEntries = 4
    AI_DEFS['PALLAS']['TIEE'].pilotCards = {'https://i.imgur.com/MczsnBQ.png','https://i.imgur.com/g6TMYWQ.png','https://i.imgur.com/zccpGoI.png','https://i.imgur.com/07RCcGC.png'}
    AI_DEFS['PALLAS']['TIEE'].elitePilotCards = {'https://i.imgur.com/MczsnBQ.png','https://i.imgur.com/g6TMYWQ.png','https://i.imgur.com/zccpGoI.png','https://i.imgur.com/07RCcGC.png'}

    AI_DEFS['HOTAC']['INT'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Interceptor',
        description = 'Alpha Squadron Pilot',
        ignoresHugeShips = true,
        mesh = 'https://paste.ee/r/JxWNX',
        diffuse = 'https://i.imgur.com/1pSXuxb.jpg',
        collider = 'https://paste.ee/r/1dx1C',
        typeColor = '88111D',
        hasFreeFocus = true,
        hasBoost = true,
        hasBarrelRoll = true,
        hasConditionalFocus = false,
        hasConditionalEvade = true,
        elitePilotSkills = {1,4, 6, 8, 10},
        elitePilotSkillDeckEntries = 6,
        pilotCards = {'https://i.imgur.com/SKX1Hge.png','https://i.imgur.com/NeP9wzw.png','https://i.imgur.com/y6M2YMQ.png','https://i.imgur.com/bKHagWB.png','https://i.imgur.com/NL4ZmKN.png','https://i.imgur.com/UfPkR0o.png'},
        elitePilotCards = {'https://i.imgur.com/SKX1Hge.png','https://i.imgur.com/NeP9wzw.png','https://i.imgur.com/y6M2YMQ.png','https://i.imgur.com/bKHagWB.png','https://i.imgur.com/NL4ZmKN.png','https://i.imgur.com/UfPkR0o.png'},
        manueverCard = 'https://i.imgur.com/2eyGeHq.jpg',
        closeMoves = {{'bl2','br2','s2','s2','k5*','k5*'},
                      {'s2','br2','br2','k5*','k5*','tr1' },
                      {'tr1','tr1','tr2','tr2','k3*','k5*'},
                      {'tr1','tr1','tr2','k3*','k5*','k5*'},
                      {'k5*','k3*','k3*','tl3','tr3','s5'}},
        farMoves =   {{'s5','s5','s5','s4','s4','s3'},
                      {'s3','br2','br3','br3','br3','tr3' },
                      {'br3','tr3','br2','tr2','tr2','tr1'},
                      {'k5*','k3*','k3*','tr2','tr2','tr1'},
                      {'k3*','k3*','k3*','k3*','tl1','tr1'}},
        fleeMoves =  {['tl1'] = 'tl3',   ['tl2'] = 'tl3',
                      ['bl2'] = 'bl3',
                      ['s2'] = 's5', ['s3'] = 's5', ['s4'] = 's5',
                      ['br2'] = 'br3',
                      ['tr1'] = 'tr3',   ['tr2'] = 'tr3',
                      ['k5*'] = 'k3*'},
        swerves =    {['tl1'] = {nil,'bl2'},   ['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                      ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                      ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},  ['s5'] = {'bl3','br3'},
                      ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                      ['tr1'] = {'br2',nil },  ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                      ['k3*'] = {'bl3','br3'}, ['k5*'] = {'bl3','br3' }}
    }
    AI_DEFS['PALLAS']['INT'] = AI_DEFS['HOTAC']['INT']

    AI_DEFS['HOTAC']['BOM'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Bomber',
        description = 'Scimitar Squadron Pilot',
        mesh = 'https://paste.ee/r/5A0YG',
        diffuse = 'http://i.imgur.com/nYO1XwT.jpg',
        collider = 'https://paste.ee/r/1dx1C',
        typeColor = 'E6E7EA',
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        elitePilotSkills = {2,3, 5, 7, 9},
        elitePilotSkillDeckEntries = 6,
        pilotCards = {'https://i.imgur.com/rrM8n0m.png','https://i.imgur.com/HeQU696.png','https://i.imgur.com/n2G8bYS.png','https://i.imgur.com/3nRaZnC.png','https://i.imgur.com/aLduj4N.png','https://i.imgur.com/0JJPWlU.png'},
        elitePilotCards = {'https://i.imgur.com/rrM8n0m.png','https://i.imgur.com/HeQU696.png','https://i.imgur.com/n2G8bYS.png','https://i.imgur.com/3nRaZnC.png','https://i.imgur.com/aLduj4N.png','https://i.imgur.com/0JJPWlU.png'},
        maneuverCard = 'https://i.imgur.com/rmp8iQm.png',
        closeMoves =   {{'bl1','br1','s1','s1','s1','k5*'},
                        {'tr3','s1','br1','br1','br1','k5*' },
                        {'br1','tr2*','tr2*','tr3','tr3','tr3'},
                        {'k5*','k5*','k5*','tr3','tr3','tr2*'},
                        {'k5*','k5*','k5*','k5*','tl3','tr3'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr3' },
                        {'br3','tr2*','tr2*','tr3','tr3','tr3'},
                        {'k5*','k5*','tr2*','tr2*','tr3','tr3'},
                        {'k5*','k5*','k5*','k5*','tl2*','tr2*'}},
        fleeMoves =    {['tl2*'] = 'tl3',
                        ['bl1'] = 'bl3',        ['bl2'] = 'bl3',
                        ['s1'] = 's4',          ['s2'] = 's4',     ['s3'] = 's4',
                        ['br1'] = 'br3',        ['br2'] = 'br3',
                        ['tr2*'] = 'tr3'},
        swerves =      {['tl2*'] = {nil,'bl2'},  ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2*','s1'}, ['bl2'] = {'tl2*','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2*'}, ['br2'] = {'s2','tr2*'}, ['br3'] = {'s3','tr3'},
                        ['tr2*'] = {'br2',nil }, ['tr3'] = {'br3',nil },
                        ['k5*'] = {'bl3','br3' }}
    }
    AI_DEFS['PALLAS']['BOM'] = AI_DEFS['HOTAC']['BOM']

    AI_DEFS['HOTAC']['ADV'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Advanced',
        description = 'Tempest Squadron Pilot',
        mesh = 'https://paste.ee/r/NeptF',
        diffuse = 'http://i.imgur.com/trxaCDg.jpg',
        collider = 'https://paste.ee/r/VAYqd',
        typeColor = 'B6274D',
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        elitePilotSkills = {2,4, 6, 8, 10},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/ykVTVFb.png','https://i.imgur.com/UeevEiT.png','https://i.imgur.com/ZeucfbB.png','https://i.imgur.com/yFuLsIU.png'},
        elitePilotCards = {'https://i.imgur.com/ykVTVFb.png','https://i.imgur.com/UeevEiT.png','https://i.imgur.com/ZeucfbB.png','https://i.imgur.com/yFuLsIU.png'},
        maneuverCard = 'https://i.imgur.com/JMCLtTP.jpg',
        closeMoves = {{'bl1','br1','s2','s2','k4*','k4*'},
                      {'s2','br1','br1','br1','k4*','k4*' },
                      {'br1','k4*','k4*','tr2','tr2','tr2'},
                      {'k4*','k4*','k4*','tr2','tr2','br1'},
                      {'k4*','k4*','k4*','k4*','tl3','tr3'}},
        farMoves =   {{'s5','s5','s5','s4','s4','s3'},
                      {'s3','br2','br3','br3','br3','tr3' },
                      {'br1','br2','tr2','tr2','tr3','tr3'},
                      {'k4*','k4*','k4*','tr2','tr2','tr2'},
                      {'k4*','k4*','k4*','k4*','tl2','tr2'}},
        fleeMoves =  {['tl2'] = 'tl3',
                        ['bl1'] = 'bl3',   ['bl2'] = 'bl3',
                        ['s2'] = 's5',     ['s3'] = 's5',     ['s4'] = 's5',
                        ['br1'] = 'br3',   ['br2'] = 'br3',
                        ['tr2'] = 'tr3'},
        swerves =    {['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s2'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},  ['s5'] = {'bl3','br3'},
                        ['br1'] = {'s2','tr2' }, ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                        ['k4*'] = {'bl3','br3' }}
    }
    AI_DEFS['PALLAS']['ADV'] = AI_DEFS['HOTAC']['ADV']

    AI_DEFS['HOTAC']['DEF'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Defender',
        description = 'Delta Squadron Pilot',
        mesh = 'https://paste.ee/r/tIm5S',
        diffuse = 'http://i.imgur.com/0u5rtnX.jpg',
        collider = 'https://paste.ee/r/6jn13',
        typeColor = '8CBCC9',
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        elitePilotSkills = {1,3, 5, 7, 9},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/p7313X7.png','https://i.imgur.com/ylcgOTT.png','https://i.imgur.com/tvCelhB.png','https://i.imgur.com/ysV9tYz.png'},
        elitePilotCards = {'https://i.imgur.com/p7313X7.png','https://i.imgur.com/ylcgOTT.png','https://i.imgur.com/tvCelhB.png','https://i.imgur.com/ysV9tYz.png'},
        maneuverCard = 'https://i.imgur.com/2i3G2E5.jpg',
        closeMoves =   {{'bl1','br1','s2','s2','k4','k4'},
                        {'s2','br1','br1','k4','k4','tr1*' },
                        {'br1','k4','k4','tr2*','tr1*','tr1*'},
                        {'k4','k4','k4','tr2*','tr2*','tr1*'},
                        {'k4','k4','k4','k4','tl3','tr3'}},
        farMoves =     {{'s5','s5','s5','s4','s4','s3'},
                        {'s3','br2','br3','br3','br3','tr3' },
                        {'br1','br2','tr2*','tr3','tr3','tr3'},
                        {'k4','k4','k4','tr2*','tr2*','tr1*'},
                        {'k4','k4','k4','k4','tl1*','tr1*'}},
        fleeMoves =    {['tl1*'] = 'tl3',  ['tl2*'] = 'tl3',
                        ['bl1'] = 'bl3',   ['bl2'] = 'bl3',
                        ['s2'] = 's5',     ['s3'] = 's5',     ['s4'] = 's5',
                        ['br1'] = 'br3',   ['br2'] = 'br3',
                        ['tr1*'] = 'tr3',  ['tr2*'] = 'tr3'},
        swerves =      {['tl1*'] = {nil,'bl1'},  ['tl2*'] = {nil,'bl2'},  ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl1*','s2'}, ['bl2'] = {'tl2*','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},  ['s5'] = {'bl3','br3'},
                        ['br1'] = {'s2','tr1*'}, ['br2'] = {'s2','tr2*'}, ['br3'] = {'s3','tr3'},
                        ['tr1*'] = {'br1',nil }, ['tr2*'] = {'br2',nil }, ['tr3'] = {'br3',nil },
                        ['k4'] = {'bl3','br3' }}
    }
    AI_DEFS['PALLAS']['DEF'] = AI_DEFS['HOTAC']['DEF']

    AI_DEFS['HOTAC']['PHA'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Phantom',
        description = 'Sigma Squadron Pilot',
        mesh = 'https://paste.ee/r/JN16g',
        diffuse = 'http://i.imgur.com/4bXBvZZ.jpg',
        collider = 'https://paste.ee/r/1dx1C',
        typeColor = 'B6F2EE',
        hasCloak = true,
        hasFreeEvade = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        hasConditionalCloak = true,
        elitePilotSkills = {3,3, 5, 7, 9},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/IkDrLGR.png','https://i.imgur.com/7kCc0Lc.png','https://i.imgur.com/SIOzwtI.png','https://i.imgur.com/KLPY5vk.png'},
        elitePilotCards = {'https://i.imgur.com/IkDrLGR.png','https://i.imgur.com/7kCc0Lc.png','https://i.imgur.com/SIOzwtI.png','https://i.imgur.com/KLPY5vk.png'},
        maneuverCard = 'https://i.imgur.com/hGk4es7.jpg',
        closeMoves =   {{'bl2','br2','s2','k4*','k4*','k4*'},
                        {'s2','br2','k4*','k4*','tr1','tr1' },
                        {'tr1','tr1','tr1','tr2','tr2','k4*'},
                        {'tr1','tr1','tr2','k3*','k4*','k4*'},
                        {'k4*','k3*','k3*','tl3','tr3','s4'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s3','br2','br3','br3','br3','tr3' },
                        {'tr1','tr1','tr2','tr2','tr3','br2'},
                        {'k4*','k3*','k3*','tr2','tr2','tr1'},
                        {'k3*','k3*','k3*','k3*','tl1','tr1'}},
        fleeMoves =    {['tl1'] = 'tl3',   ['tl2'] = 'tl3',
                        ['bl2'] = 'bl3',
                        ['s2'] = 's4',     ['s3'] = 's4',
                        ['br2'] = 'br3',
                        ['tr1'] = 'tr3',   ['tr2'] = 'tr3',
                        ['k4*'] = 'k3*'},
        swerves =      {['tl1'] = {nil,'bl2'},   ['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},
                        ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr1'] = {'br2',nil },  ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                        ['k3*'] = {'bl3','br3'}, ['k4*'] = {'bl3','br3' }}
    }
    AI_DEFS['PALLAS']['PHA'] = AI_DEFS['HOTAC']['PHA']

    AI_DEFS['HOTAC']['DEC'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'VT-49 Decimator',
        description = 'Patrol Leader',
        isLargeShip = true,
        mesh = 'https://paste.ee/r/MJOFI',
        diffuse = 'http://i.imgur.com/atzM3rO.jpg',
        collider = 'https://paste.ee/r/JavTd',
        typeColor = '2E3543', --808080',
        has360Turret = true,
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        elitePilotSkills = {3, nil, nil, nil, nil},
        elitePilotSkillDeckEntries = 1,
        pilotCards = {'https://i.imgur.com/aNJiVl9.png'},
        maneuverCard = 'https://i.imgur.com/gg8HD8T.jpg',
        closeMoves =   {{'s4','s4','bl3','br3','tl3','tr3'},
                        {'br3','bl3','bl2','tl2','s4','s4' },
                        {'br3','br3','tr3','br2','tr2','br1'},
                        {'br3','br3','tr2','tr2','br2','br1'},
                        {'tl3','tr3','tl2','tr2','bl1','br1'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s4','br3','br3','br3','br2','tr3' },
                        {'br3','tr3','tr3','tr2','tr2','br1'},
                        {'tr2','tr2','tr2','tr3','tr3','br1'},
                        {'tl2','tl2','tl2','tr2','tr2','tr2'}},
        fleeMoves =    {['tl2'] = 'tl3',
                        ['bl1'] = 'bl3',   ['bl2'] = 'bl3',
                        ['s1'] = 's4',     ['s2'] = 's4', ['s3'] = 's4',
                        ['br1'] = 'br3',   ['br2'] = 'br3',
                        ['tr2'] = 'tr3'},
        swerves =      {['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil }}
    }
    AI_DEFS['PALLAS']['DEC'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['HOTAC']['DEC']))
    AI_DEFS['PALLAS']['DEC'].description = 'Patrol Leader (Elite)'
    AI_DEFS['PALLAS']['DEC'].elitePilotSkills = {2,4,5,7,9}
    AI_DEFS['PALLAS']['DEC'].elitePilotSkillDeckEntries = 4
    AI_DEFS['PALLAS']['DEC'].pilotCards = {'https://i.imgur.com/p4QjitY.png','https://i.imgur.com/3hIY2CE.png','https://i.imgur.com/Y9oLlN7.png','https://i.imgur.com/e8HoQzQ.png'}
    AI_DEFS['PALLAS']['DEC'].elitePilotCards = {'https://i.imgur.com/p4QjitY.png','https://i.imgur.com/3hIY2CE.png','https://i.imgur.com/Y9oLlN7.png','https://i.imgur.com/e8HoQzQ.png'}

    AI_DEFS['HOTAC']['SHU'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'Lambda-Class Shuttle',
        description = 'Omicron Group Pilot',
        isLargeShip = true,
        mesh = 'https://paste.ee/r/4uxZO',
        diffuse = 'http://i.imgur.com/rd9ZPz3.jpg',
        collider = 'https://paste.ee/r/xBpMo',
        typeColor = 'DCDCDC',
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        elitePilotSkills = {2,4, 4, 6, 8},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/sxplWWh.png','https://i.imgur.com/tWHUaj2.png','https://i.imgur.com/iMb9VLT.png','https://i.imgur.com/G3L67Kc.png'},
        elitePilotCards = {'https://i.imgur.com/sxplWWh.png','https://i.imgur.com/tWHUaj2.png','https://i.imgur.com/iMb9VLT.png','https://i.imgur.com/G3L67Kc.png'},
        manueverCard = 'https://i.imgur.com/kMkJ8U0.jpg',
        closeMoves =   {{'s0*','s0*','s0*','s1','br1','bl1'},
                        {'s0*','s1','br1','br1','br1','tr2*' },
                        {'s0*','tr2*','tr2*','tr2*','br1','br2'},
                        {'s0*','tr2*','tr2*','tr2*','br2','br3*'},
                        {'s0*','*','tr2*','tl2*','br3*','bl3*'}},
        farMoves =     {{'s3','s3','s3','s2','s2','s1'},
                        {'s2','br3*','br2','br2','br2','tr2*' },
                        {'tr2*','tr2*','tr2*','tr2*','br2','br3*'},
                        {'tr2*','tr2*','tr2*','tr2*','br1','br1'},
                        {'tl2*','tl2*','tl2*','tr2*','tr2*','tr2*'}},
        fleeMoves =    {['bl1']='bl3*',['bl2']='bl3*',
                        ['s0*']='s3',['s1']='s3',['s2']='s3',
                        ['br1']='br3*',['br2']='br3*'},
        swerves =      {['tl2*'] = {nil,'bl2'},
                        ['bl1'] = {'tl2*','s1'}, ['bl2'] = {'tl2*','s2'}, ['bl3*'] = {'tl2*','s3'},
                        ['s0*'] = {'bl1','br1'}, ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3*','br3*'},
                        ['br1'] = {'s1','tr2*'}, ['br2'] = {'s2','tr2*'}, ['br3*'] = {'s3','tr2*'},
                        ['tr2*'] = {'br2',nil} }

    }
    AI_DEFS['PALLAS']['SHU'] = AI_DEFS['HOTAC']['SHU']

    AI_DEFS['PALLAS']['TFO'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE/fo Fighter',
        description = 'Epsilon Squadron Pilot',
        ignoresHugeShips = true,
        mesh = 'http://pastebin.com/jt2AzA8t',
        diffuse = 'http://i.imgur.com/z56FaVi.png',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '979DAD',
        hasFreeFocus = true,
        hasBarrelRoll = true,
        hasConditionalEvade = true,
        hasConditionalFocus = false,
        hasConditionalTargetLock = true,
        elitePilotSkills = {2, nil, nil, nil, nil},
        elitePilotSkillDeckEntries = 1,
        pilotCards = {'https://i.imgur.com/rGEJOvs.png'},
        maneuverCard = 'https://i.imgur.com/de63qdW.png',
        closeMoves =   {{'bl2','br2','s2','s2','k4*','k4*'},
                        {'s2','br2','br2','k4*','k4*','tr1' },
                        {'tr1','tr1','tr2','tr2','br2s*','br2s*'},
                        {'tr1','tr1','tr2','br2s*','br2s*','k4*'},
                        {'k4*','br2s*','bl2s*','tl3','tr3','s5'}},
        farMoves =     {{'s5','s5','s5','s4','s4','s3'},
                        {'s3','br2','br3','br3','br3','tr3' },
                        {'tr3','tr3','br2','br2','tr2','tr2'},
                        {'br2s*','k4*','k4*','tr2','tr2','tr2'},
                        {'k4*','k4*','br2s*','bl2s*','tl1','tr1'}},
        fleeMoves =    {['tl1'] = 'tl3',   ['tl2'] = 'tl3',
                        ['bl2'] = 'bl3',
                        ['s2'] = 's5',     ['s3'] = 's5', ['s4'] = 's5',
                        ['br2'] = 'br3',
                        ['tr1'] = 'tr3',   ['tr2'] = 'tr3'},
        swerves =      {['tl1'] = {nil,'bl2'},   ['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},  ['s5'] = {'bl3','br3'},
                        ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr1'] = {'br2',nil },  ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                        ['bl2s*'] = {'tl2','k4*'},
                        ['k4*'] = {'bl2s*','br2s*'},
                        ['br2s*'] = {'k4*','tr2'} } }
    AI_DEFS['PALLAS']['TFOE'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['TFO']))
    AI_DEFS['PALLAS']['TFOE'].description = "Omega Squadron Pilot"
    AI_DEFS['PALLAS']['TFOE'].elitePilotSkills = {2, 4, 5, 7, 9}
    AI_DEFS['PALLAS']['TFOE'].elitePilotSkillDeckEntries = 4
    AI_DEFS['PALLAS']['TFOE'].pilotCards = {'https://i.imgur.com/MczsnBQ.png','https://i.imgur.com/g6TMYWQ.png','https://i.imgur.com/zccpGoI.png','https://i.imgur.com/07RCcGC.png'}
    AI_DEFS['PALLAS']['TFOE'].elitePilotCards = {'https://i.imgur.com/MczsnBQ.png','https://i.imgur.com/g6TMYWQ.png','https://i.imgur.com/zccpGoI.png','https://i.imgur.com/07RCcGC.png'}

    --TODO: UPS Upsilon Shuttle
    AI_DEFS['PALLAS']['UPS'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'Upsilon Class Shuttle',
        description = 'Starkiller Base Pilot',
        isLargeShip = true,
        mesh = 'http://pastebin.com/nsHXF9XV',
        diffuse = 'http://cloud-3.steamusercontent.com/ugc/200804344074733139/9D83653AAE1963E2C4945712860F5B47D2B41415/',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964883/B11F61E5ED25B90F87C047EB6252D3B18EBB09F1/',
        typeColor = '58595B',
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        elitePilotSkills = {2, nil, nil, nil, nil}, --UPS should be 2 not 1
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/5duITLw.png'},
        maneuverCard = 'https://i.imgur.com/tbIVQzC.png',
        closeMoves = {{'s0*','s0*','s0*','s1','br1','bl1'},
                      {'s0*','s1','br1','br1','br1','tr2'},
                      {'s0*','tr2','tr2','tr2','br1','br2'},
                      {'s0*','tr2','tr2','tr2','br2','br3'},
                      {'s0*','s0*','tr1*','tl1*','br3','bl3'}},
        farMoves = {{'s3','s3','s3','s2','s2','s1'},
                    {'tr2','br3','br2','br2','br2','tr3*'},
                    {'tr2','tr2','tr2','tr2','br2','br3'},
                    {'tr2','tr2','tr2','tr2','br2','br2'},
                    {'tl2','tl2','tl2','tr2','tr2','tr2'}},
        fleeMoves = {['tl1*'] = 'tl3*', ['tl2'] = 'tl3*',
                     ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                     ['s0*'] = 's3', ['s1'] = 's3', ['s2'] = 's3',
                     ['br1'] = 'br3', ['br2'] = 'br3',
                     ['tr1*'] = 'tr3*', ['tr2'] = 'tr3*'},
        swerves = {['tl1*'] = {nil, 'bl1'}, ['tl2'] = {nil, 'bl2'}, ['tl3*'] = {nil, 'bl3'},
                   ['bl1'] = {'tl1*','s1'}, ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3*','s3'},
                   ['s0*'] = {'bl1','br1'},  ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},
                   ['br1'] = {'s1','tr1*'}, ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3*'},
                   ['tr1*'] = {'br1', nil}, ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil}}
    }
    --TODO: TAP TIE Adv. Prototype
    AI_DEFS['PALLAS']['TAP'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Adv. Prototype',
        description = 'Sienar Test Pilot',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029089434/A4DA1AD96E4A6D65CC6AE4F745EDA966BA4EF85A/',
        diffuse = 'http://i.imgur.com/7vyhllx.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'E42635',
        hasFreeBarrelRoll = true,
        hasBoost = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        hasConditionalTargetLock = true,
        elitePilotSkills = {2,4,5,7,9},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/ZT9Wuir.png','https://i.imgur.com/DdH4y8B.png','https://i.imgur.com/yHA8H15.png','https://i.imgur.com/aQZX639.png'},
        elitePilotCards = {'https://i.imgur.com/ZT9Wuir.png','https://i.imgur.com/DdH4y8B.png','https://i.imgur.com/yHA8H15.png','https://i.imgur.com/aQZX639.png'},
        maneuverCard = 'https://i.imgur.com/UrVyKu1.png',
        closeMoves = {{'bl1','br1','s2','s2','k4*','k4*'},
                      {'s2','tr2','tr2','k4*','k4*','tr1'},
                      {'tr3','tr2','tr2','tr1','tr1','tr1'},
                      {'k4*','k4*','k4*','tr1','tr1','tr2'},
                      {'tr1','tr1','tl1','tl1','k4*','s5'}},
        farMoves = {{'s5','s5','s5','s4','s4','s3'},
                    {'s2','br2','br3','br3','br3','tr3'},
                    {'br3','br2','tr3','tr3','tr2','tr1'},
                    {'tr1','tr2','tr3','k4*','k4*','k4*'},
                    {'k4*','k4*','k4*','k4*','tl1','tr1'}},
        fleeMoves = {['tl1'] = 'tl3', ['tl2'] = 'tl3',
                     ['bl1'] = 'bl3',   ['bl2'] = 'bl3',
                     ['s2'] = 's5',     ['s3'] = 's5',     ['s4'] = 's5',
                     ['br1'] = 'br3',   ['br2'] = 'br3',
                     ['tr1'] = 'tr3',  ['tr2'] = 'tr3'},
        swerves =    {['tl1'] = {nil,'bl1'},   ['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                      ['bl1'] = {'tl1','s2'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                      ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},  ['s5'] = {'bl3','br3'},
                      ['br1'] = {'s2','tr1'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                      ['tr1'] = {'br1',nil },  ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                      ['k4*'] = {'bl3','br3'}}
    }
    --TODO: TSF TIE S/F
    AI_DEFS['PALLAS']['TSF'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE/sf Fighter',
        description = 'Zeta Specialist',
        mesh = 'http://pastebin.com/LezDjunY',
        diffuse = 'http://i.imgur.com/x8NveGf.png',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '6693CA',
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        elitePilotSkills = {3,nil,nil,nil,nil}, --TODO: TSF should be 3 not 2?
        elitePilotSkillDeckEntries = 1,
        pilotCards = {'https://i.imgur.com/v5lpoke.png'},
        maneuverCard = 'https://i.imgur.com/WmoBrcN.png',
        closeMoves =   {{'s1','s1','br3','br3','bl3','bl3'},
                        {'s1','bl3s*','bl3s*','tl3*','tl3*','tr2'},
                        {'tr1*','tr1*','tr1*','bl3s*','bl3s*','tr2'},
                        {'br1','br1','tr2','tr2','tr1*','bl3s*'},
                        {'bl3s*','br3s*','tr2','tl2','br3','bl3'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','tr3*','br3','br3','br2','br2'},
                        {'br3','br2','tr3*','tr3*','tr2','tr2'},
                        {'br2','tr2','tr3*','tr3*','bl3s*','bl3s*'},
                        {'bl3s*','br3s*','tr2','tr2','tl2','tl2'}},
        fleeMoves = {['tl1*'] = 'tl3*', ['tl2'] = 'tl3*',
                     ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                     ['s1'] = 's4', ['s2'] = 's4', ['s3'] = 's4',
                     ['br1'] = 'br3', ['br2'] = 'br3',
                     ['tr1*'] = 'tr3*', ['tr2'] = 'tr3*'},
        swerves = {['tl1*'] = {nil, 'bl1'}, ['tl2'] = {nil, 'bl2'}, ['tl3*'] = {nil, 'bl3'},
                   ['bl1'] = {'tl1*','s1'}, ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3*','s3'},
                   ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},  ['s4'] = {'bl3','br3'},
                   ['br1'] = {'s1','tr1*'}, ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3*'},
                   ['tr1*'] = {'br1', nil}, ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil},
                   ['bl3s*'] = {'tl3*','s3'},
                   ['br3s*'] = {'s3','tr3*'} } }
    --TODO: PUN Punisher
    AI_DEFS['PALLAS']['PUN'] = HostileAiDefinition:new{
        faction = EMPIRE,
        shipType = 'TIE Punisher',
        description = 'Cutlass Squadron Pilot',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029073355/7A1507E4D88098D19C8EAFE4A763CC33A5EC35CB/',
        diffuse = 'http://i.imgur.com/r6bfxcV.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '008F8F',
        hasFreeTargetLock = true,
        hasBoost = true,
        hasConditionalFocus = true,
        elitePilotSkills = {2,4,5,7,9},
        elitePilotSkillDeckEntries = 4,
        pilotCards = {'https://i.imgur.com/6nFuHsX.png','https://i.imgur.com/OtfAiKo.png','https://i.imgur.com/w9o88sJ.png','https://i.imgur.com/QWVP5ja.png'},
        elitePilotCards = {'https://i.imgur.com/6nFuHsX.png','https://i.imgur.com/OtfAiKo.png','https://i.imgur.com/w9o88sJ.png','https://i.imgur.com/QWVP5ja.png'},
        maneuverCard = 'https://i.imgur.com/X3NRZOJ.png',
        closeMoves =   {{'bl1','br1','s1','s1','s1','k4*'},
                        {'tr3','s1','br1','br1','br1','k5*'},
                        {'br1','tr2*','tr2*','tr3','tr3','tr3'},
                        {'k4*','k4*','k4*','tr3','tr3','tr2*'},
                        {'k4*','k4*','k4*','k4*','tl3','tr3'}},
        farMoves =     {{'s3','s3','s3','s3','s2','s2'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'br3','tr2*','tr2*','tr3','tr3','tr3'},
                        {'k4*','k4*','tr2*','tr2*','tr3','tr3'},
                        {'k5*','k5*','k5*','k5*','tl2*','tr2*'}},
        fleeMoves =    {['tl2*'] = 'tl3',
                     ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                     ['s1'] = 's3', ['s2'] = 's3',
                     ['br1'] = 'br3', ['br2'] = 'br3',
                     ['tr2*'] = 'tr3'},
        swerves =    {['tl2*'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                      ['bl1'] = {'tl2*','s1'},  ['bl2'] = {'tl2*','s2'},  ['bl3'] = {'tl3','s3'},
                      ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'},
                      ['br1'] = {'s1','tr2*'},  ['br2'] = {'s2','tr2*'},  ['br3'] = {'s3','tr3'},
                      ['tr2*'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                      ['k4*'] = {'bl3','br3'}}
    }
    --TODO: BWI B-wing
    AI_DEFS['PALLAS']['BBLU'] = FriendlyAiDefinition:new{
        faction = REBELLION,
        shipType = 'B-Wing',
        description = 'Blue Squadron Pilot (Wingman)',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029071704/78677576E07A2F091DEC4CE58129B42714E8A19E/',
        diffuse = 'http://i.imgur.com/JihQH1r.png',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '33567D',
        hasFreeFocus = true,
        hasBarrelRoll = true,
        hasConditionalFocus = false,
        hasConditionalTargetLock = true,
        elitePilotSkills = {2,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/5DsudGv.png'},
        maneuverCard = 'https://i.imgur.com/IekqYGr.png',
        closeMoves =   {{'bl1','br1','s1','s1','s1','k2*'},
                        {'tr1*','s1','br1','br1','br1','br2'},
                        {'tr1*','tr1*','tr2','tr2','k2*','k2*'},
                        {'k2*','k2*','k2*','tr2','tr2','tr1*'},
                        {'tr1*','s3','tl1*','k2*','k2*','k2*'}},
        farMoves =     {{'s3','s3','s3','s2','s2','s4*'},
                        {'s2','br2','br2','tr2','tr2','br3*'},
                        {'br3*','tr2','tr2','tr2','tr1*','tr1*'},
                        {'k2*','k2*','tr2','tr2','tr2','tr1*'},
                        {'k2*','k2*','k2*','k2*','tl2','tr2'}},
        fleeMoves = {['tl1*'] = 'tl2',
                     ['bl1'] = 'bl3*',['bl2'] = 'bl3*',
                     ['s1'] = 's4*', ['s2'] = 's4*',['s3'] = 's4*',
                     ['br1'] = 'br3*',['br2'] = 'br3*',
                     ['tr1*'] = 'tr2'},
        swerves =   {['tl1*'] = {nil,'bl1'},   ['tl2'] = {nil,'bl2'},
                     ['bl1'] = {'tl1*','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3*'] = {'tl2','s3'},
                     ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3*','br3*'}, ['s4*'] = {'bl3*','br3*'},
                     ['br1'] = {'s1','tr1*'},  ['br2'] = {'s2','tr2'},  ['br3*'] = {'s3','tr2'},
                     ['tr1*'] = {'br1',nil },  ['tr2'] = {'br2',nil },
                     ['k2*'] = {'bl2','br2'}},
        hyperdriveMoves = {'s1','s1','s2','s2','br1','bl1'}
    }
    AI_DEFS['DOTE']['BBLU'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['BBLU']))
    AI_DEFS['DOTE']['BBLU'].description = 'Blue Squadron Pilot'
    AI_DEFS['DOTE']['BBLU'].elitePilotSkills = {2,5,6,8,10}
    AI_DEFS['DOTE']['BBLU'].eliteLimits = {6,8,10}
    AI_DEFS['DOTE']['BBLU'].maneuverCard = 'https://i.imgur.com/zKziUHr.png'
    AI_DEFS['DOTE']['BBLU'].elitePilotCards = {'https://i.imgur.com/kiiEkpm.png','https://i.imgur.com/LfVhcn6.png'}
    AI_DEFS['DOTE']['BBLU'].alternate = 'BDAG'
    AI_DEFS['DOTE']['BBLU'].alternateLevel = 6
    AI_DEFS['DOTE']['BDAG'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['BBLU']))
    AI_DEFS['DOTE']['BDAG'].description = 'Dagger Squadron Pilot'
    AI_DEFS['DOTE']['BDAG'].elitePilotSkills = {4,5,6,8,10}
    AI_DEFS['DOTE']['BDAG'].pilotCards = {'https://i.imgur.com/TRKukz4.png'}
    AI_DEFS['DOTE']['BDAG'].maneuverCard = 'https://i.imgur.com/hRxWqim.png'
    AI_DEFS['DOTE']['BDAG'].alternate = nil
    AI_DEFS['DOTE']['BDAG'].alternateLevel = nil
    -- AI_DEFS['DOTE']['BDAG'].elitePilotSkillDeckEntries = 2

    AI_DEFS['PALLAS']['ZBAN'] = FriendlyAiDefinition:new{
        faction = REBELLION,
        shipType = 'Z-95 Headhunter Rebel',
        description = 'Bandit Squadron Pilot (Wingman)',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029075380/02AE170F8A35A5619E57B3380F9F7FE0E127E567/',
        diffuse = 'http://i.imgur.com/hcCxX3n.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'FDCC7C',
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        elitePilotSkills = {2,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/aq19z7u.png'},
        maneuverCard = 'https://i.imgur.com/iBp0ZXu.png',
        closeMoves =   {{'bl1','br1','s1','s1','s1','k3*'},
                        --{'br2','s1','br1','br1','k3*','k3*'}, --PALLAS Version
                        {'br2','s2','br3','br3','k3*','k3*'}, --DOTE Version
                        {'br1','tr2','tr2','tr2','k3*','k3*'},
                        {'k3*','k3*','k3*','tr2','tr2','tr3'},
                        {'k3*','k3*','k3*','tl2','tr2','s4'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        --{'br3','tr2','tr2','tr2','tr3','tr3'}, --PALLAS Version
                        {'br2','tr2','tr2','tr2','tr3','tr3'}, --DOTE Version
                        {'k3*','k3*','tr2','tr2','tr2','tr3'},
                        {'k3*','k3*','k3*','k3*','tl2','tr2'}},
        fleeMoves =    {['tl2'] = 'tl3',
                        ['bl1'] = 'bl3',['bl2'] = 'bl3',
                        ['s1'] = 's4', ['s2'] = 's4',['s3'] = 's4',
                        ['br1'] = 'br3',['br2'] = 'br3',
                        ['tr2'] = 'tr3'},
        swerves =      {['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                        ['k3*'] = {'bl3','br3'}},
        hyperdriveMoves = {'s1','s1','s2','s2','br2','bl2'}
    }
    AI_DEFS['DOTE']['ZBAN'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['ZBAN']))
    AI_DEFS['DOTE']['ZBAN'].description = 'Bandit Squadron Pilot'
    AI_DEFS['DOTE']['ZBAN'].maneuverCard = 'https://i.imgur.com/ZiqX7r2.png'
    AI_DEFS['DOTE']['ZBAN'].alternate = 'ZTAL'
    AI_DEFS['DOTE']['ZBAN'].alternateLevel = 5
    AI_DEFS['DOTE']['ZTAL'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['ZBAN']))
    AI_DEFS['DOTE']['ZTAL'].description = 'Tala Squadron Pilot'
    AI_DEFS['DOTE']['ZTAL'].elitePilotSkills = {4,nil,nil,nil,nil}
    AI_DEFS['DOTE']['ZTAL'].hasFreeFocus = true
    AI_DEFS['DOTE']['ZTAL'].hasConditionalFocus = false
    AI_DEFS['DOTE']['ZTAL'].hasConditionalTargetLock = true
    AI_DEFS['DOTE']['ZTAL'].pilotCards = {'https://i.imgur.com/cOYaDzo.png'}
    AI_DEFS['DOTE']['ZTAL'].maneuverCard = 'https://i.imgur.com/sbFF2TV.png'
    AI_DEFS['DOTE']['ZTAL'].alternate = nil
    AI_DEFS['DOTE']['ZTAL'].alternateLevel = nil
    AI_DEFS['DOTE']['ZBIN'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['ZBAN']))
    AI_DEFS['DOTE']['ZBIN'].faction = SCUM
    AI_DEFS['DOTE']['ZBIN'].shipType = 'Z-95 Headhunter Scum'
    AI_DEFS['DOTE']['ZBIN'].description = 'Binayre Pirate'
    AI_DEFS['DOTE']['ZBIN'].elitePilotSkills = {1,nil,nil,nil,nil}
    AI_DEFS['DOTE']['ZBIN'].hasBarrelRoll = false
    AI_DEFS['DOTE']['ZBIN'].hasConditionalTargetLock = false
    AI_DEFS['DOTE']['ZBIN'].pilotCards = {'https://i.imgur.com/wqJyuEh.png'}
    AI_DEFS['DOTE']['ZBIN'].maneuverCard = 'https://i.imgur.com/fxWBXx0.png'
    AI_DEFS['DOTE']['ZBIN'].alternate = 'ZBLA'
    AI_DEFS['DOTE']['ZBIN'].alternateLevel = 4
    AI_DEFS['DOTE']['ZBLA'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['ZBIN']))
    AI_DEFS['DOTE']['ZBLA'].description = 'Black Sun Soldier'
    AI_DEFS['DOTE']['ZBLA'].elitePilotSkills = {3,nil,nil,nil,nil}
    AI_DEFS['DOTE']['ZBLA'].hasConditionalTargetLock = true
    AI_DEFS['DOTE']['ZBLA'].pilotCards = {'https://i.imgur.com/fEmvLdA.png'}
    AI_DEFS['DOTE']['ZBLA'].maneuverCard = 'https://i.imgur.com/r3e3UkP.png'
    AI_DEFS['DOTE']['ZBLA'].alternate = nil
    AI_DEFS['DOTE']['ZBLA'].alternateLevel = nil

    AI_DEFS['PALLAS']['XRED'] = FriendlyAiDefinition:new{--x-wing T-65
        faction = REBELLION,
        shipType = 'X-Wing',
        description = 'Red Squadron Pilot (Wingman)',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029083210/BFF5BAE2A45EC9D647E14D9041140FFE114BF2D4/',
        diffuse = 'http://i.imgur.com/3GxuDDz.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '8B392E',
        hasFreeFocus = true,
        hasConditionalTargetLock = true,
        elitePilotSkills = {4,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/LQQFQqG.png'},
        maneuverCard = 'https://i.imgur.com/pdW0dQu.png',
        closeMoves =   {{'bl1','br1','s1','s1','s1','k4*'},
                        {'tr2','s1','br1','br1','k4*','k4*'},
                        {'br1','tr2','tr2','tr3','k4*','k4*'},
                        {'k4*','k4*','k4*','tr2','tr2','tr3'},
                        {'k4*','k4*','k4*','tl2','tr2','s4'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'br3','tr2','tr2','tr2','tr3','tr3'},
                        {'k4*','k4*','tr2','tr2','tr2','tr3'},
                        {'k4*','k4*','k4*','k4*','tl2','tr2'}},
        fleeMoves = {['tl2'] = 'tl3',
                     ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                     ['s1'] = 's4', ['s2'] = 's4', ['s3'] = 's4',
                     ['br1'] = 'br3', ['br2'] = 'br3',
                     ['tr2'] = 'tr3'},
        swerves = {['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                      ['bl1'] = {'tl2','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                      ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                      ['br1'] = {'s1','tr2'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                      ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                      ['k4*'] = {'bl3','br3'}},
        hyperdriveMoves = {'s1','s1','s2','s2','br1','bl1'}
    }
    AI_DEFS['DOTE']['XROO'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['XRED']))
    AI_DEFS['DOTE']['XROO'].description = 'Rookie Pilot'
    AI_DEFS['DOTE']['XROO'].hasFreeFocus = false
    AI_DEFS['DOTE']['XROO'].hasConditionalFocus = true
    AI_DEFS['DOTE']['XROO'].hasConditionalTargetLock = false
    AI_DEFS['DOTE']['XROO'].elitePilotSkills = {2,5,6,8,10}
    AI_DEFS['DOTE']['XROO'].eliteLimits = {6,8,10}
    AI_DEFS['DOTE']['XROO'].pilotCards = {'https://i.imgur.com/zomP7IU.png'}
    AI_DEFS['DOTE']['XROO'].elitePilotCards = {'https://i.imgur.com/ghc8pT0.png','https://i.imgur.com/1hodCHu.png','https://i.imgur.com/yiURYiv.png','https://i.imgur.com/M1pEqNW.png'}
    AI_DEFS['DOTE']['XROO'].maneuverCard = 'https://i.imgur.com/BDMeI4U.png'
    AI_DEFS['DOTE']['XROO'].alternate = 'XRED'
    AI_DEFS['DOTE']['XROO'].alternateLevel = 5
    AI_DEFS['DOTE']['XRED'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['XROO']))
    AI_DEFS['DOTE']['XRED'].description = 'Red Squadron Pilot'
    AI_DEFS['DOTE']['XRED'].hasFreeFocus = true
    AI_DEFS['DOTE']['XRED'].hasConditionalFocus = false
    AI_DEFS['DOTE']['XRED'].hasConditionalTargetLock = true
    AI_DEFS['DOTE']['XRED'].elitePilotSkills = {4,5,6,8,10}
    AI_DEFS['DOTE']['XRED'].pilotCards = {'https://i.imgur.com/LQQFQqG.png'}
    AI_DEFS['DOTE']['XRED'].maneuverCard = 'https://i.imgur.com/Nppukw0.png'
    AI_DEFS['DOTE']['XRED'].alternate = nil
    AI_DEFS['DOTE']['XRED'].alternateLevel = nil
    -- AI_DEFS['DOTE']['XRED'].elitePilotSkillDeckEntries = 4

    AI_DEFS['PALLAS']['EBLM'] = FriendlyAiDefinition:new{ --E-Wing Blackmoon
        faction = REBELLION,
        shipType = 'E-Wing',
        description = 'Blackmoon Squadron Pilot (Wingman)',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029072231/46CA6A77D12681CA1B1B4A9D97BD6917811D561C/',
        diffuse = 'http://i.imgur.com/TItm60V.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'B9302B',
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        elitePilotSkills = {3,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/liYcDCm.png'},
        maneuverCard = 'https://i.imgur.com/IbyeUFI.png',
        closeMoves =   {{'bl1','br1','s1','s1','k4*','k4*'},
                        {'k3*','s1','br1','br1','k4*','k4*'},
                        {'br1','tr1','tr1','tr1','k3*','k4*'},
                        {'k3*','k3*','k3*','tr2','k4*','k4*'},
                        {'k3*','k4*','k4*','tl3','tr3','s5'}},
        farMoves =     {{'s5','s5','s5','s4','s4','s3'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'br3','tr2','tr2','tr2','tr3','tr3'},
                        {'k4*','k4*','tr2','tr2','k3*','k3*'},
                        {'k3*','k3*','k3*','k3*','tl3','tr3'}},
        fleeMoves =    {['tl2'] = 'tl3',
                        ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                        ['s1'] = 's5', ['s2'] = 's5', ['s3'] = 's5', ['s4'] = 's5',
                        ['br1'] = 'br3', ['br2'] = 'br3',
                        ['tr2'] = 'tr3',
                        ['k4*'] = 'k3*'},
        swerves =      {['tl2'] = {nil,'bl2'},   ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'}, ['s5'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil },  ['tr3'] = {'br3',nil },
                        ['k3*'] = {'bl3','br3'}, ['k4*'] = {'bl3','br3'}},
        hyperdriveMoves = {'s1','s2','s3','s3','br1','bl1'}
    }
    AI_DEFS['DOTE']['EKNA'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['EBLM']))
    AI_DEFS['DOTE']['EKNA'].description = 'Knave Squadron Pilot'
    AI_DEFS['DOTE']['EKNA'].elitePilotSkills = {1,5,6,8,10}
    AI_DEFS['DOTE']['EKNA'].eliteLimits = {6,8,10}
    AI_DEFS['DOTE']['EKNA'].pilotCards = {'https://i.imgur.com/Xgd94rV.png'}
    AI_DEFS['DOTE']['EKNA'].elitePilotCards = {'https://i.imgur.com/0fYxjMx.png','https://i.imgur.com/mSELDWS.png'}
    AI_DEFS['DOTE']['EKNA'].maneuverCard = 'https://i.imgur.com/4cgzz5H.png'
    AI_DEFS['DOTE']['EKNA'].alternate = 'EBLM'
    AI_DEFS['DOTE']['EKNA'].alternateLevel = 7
    AI_DEFS['DOTE']['EBLM'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['EBLM']))
    AI_DEFS['DOTE']['EBLM'].description = 'Blackmoon Squadron Pilot'
    AI_DEFS['DOTE']['EBLM'].hasFreeEvade = true
    AI_DEFS['DOTE']['EBLM'].elitePilotSkills = {3,5,6,8,10}
    AI_DEFS['DOTE']['EBLM'].maneuverCard = 'https://i.imgur.com/Py1HNlu.png'
    AI_DEFS['DOTE']['EBLM'].alternate = nil
    AI_DEFS['DOTE']['EBLM'].alternateLevel = nil
    -- AI_DEFS['DOTE']['EBLM'].elitePilotSkillDeckEntries = 2

    AI_DEFS['DOTE']['KWAR'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'K-Wing',
        description = 'Warden Squadron Pilot',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029069099/CDF24012FD0342ED8DE472CFA0C7C2748E3AF541/',
        diffuse = 'http://i.imgur.com/gi6Ju20.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'E4834D',
        hasFreeFocus = true,
        hasConditionalTargetLock = true,
        hasConditionalSlam = true,
        elitePilotSkills = {2,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/0ZkTCON.png'},
        maneuverCard = 'https://i.imgur.com/ZDl8RA1.png',
        closeMoves =   {{'s3','s3','br2','bl2','tr2','tl2'},
                        {'bl2','tl2','br2','br2','s3','s3'},
                        {'br3','br2','br2','tr2','br1','br1'},
                        {'br3','br2','br2','tr2','tr2','br1'},
                        {'tl2','tl2','tr2','tr2','bl1','br1'}},
        farMoves =     {{'s3','s3','s3','s3','s2','s2'},
                        {'s3','br2','br2','br3','br3','tr2'},
                        {'br3','br2','br2','tr2','tr2','br1'},
                        {'tr2','tr2','tr2','br2','br2','br1'},
                        {'tl2','tl2','tl2','tr2','tr2','tr2'}},
        fleeMoves =    {['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s3',['s2']='s3',
                        ['br1']='br3',['br2']='br3'},
        swerves =      {['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr2'] = {'br2',nil} },
        hyperdriveMoves = {}, --NO HYPERDRIVE
        alternate = "KGUA",
        alternateLevel = 7
    }
    AI_DEFS['DOTE']['KGUA'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['KWAR']))
    AI_DEFS['DOTE']['KGUA'].description = 'Guardian Squadron Pilot'
    AI_DEFS['DOTE']['KGUA'].hasFreeFocus = false
    AI_DEFS['DOTE']['KGUA'].hasFreeTargetLock = true
    AI_DEFS['DOTE']['KGUA'].hasConditionalFocus = true
    AI_DEFS['DOTE']['KGUA'].elitePilotSkills = {4,nil,nil,nil,nil}
    AI_DEFS['DOTE']['KGUA'].pilotCards = {'https://i.imgur.com/tB2abEL.png'}
    AI_DEFS['DOTE']['KGUA'].maneuverCard = 'https://i.imgur.com/Rhiwi7l.png'

    AI_DEFS['DOTE']['YGOL'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'Y-Wing Rebel',
        description = 'Gold Squadron Pilot',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029097150/75A486189FEDE8BEEBFBACC0D76DE926CB42E52A/',
        diffuse = 'http://i.imgur.com/x5zYjn5.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'B1991F',
        hasConditionalTargetLock = true,
        elitePilotSkills = {2,5,6,8,10},
        eliteLimits = {6,8,10},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/8ANZBkm.png'},
        elitePilotCards = {'https://i.imgur.com/byyt0V9.png','https://i.imgur.com/ciR5NKa.png'},
        maneuverCard = 'https://i.imgur.com/6pEocZh.png',
        closeMoves =   {{'bl1','br1','s1','s1','tl2','tr2'},
                        {'tr2','tr2','s1','br1','br1','br1'},
                        {'br1','tr2','tr2','tr2','tr3*','tr3*'},
                        {'k4*','k4*','k4*','tr2','tr2','tr3*'},
                        {'k4*','k4*','k4*','tl2','tr2','s3'}},
        farMoves =     {{'s4*','s3','s3','s3','s2','s2'},
                        {'s2','br2','br3','br3','tr2','tr2'}, --assuming 2nd row of br2 is acutally br3
                        {'br3','tr2','tr2','tr2','tr3*','tr3*'},
                        {'k4*','k4*','tr2','tr2','tr2','tr3*'},
                        {'k4*','k4*','k4*','k4*','tl2','tr2'}},
        fleeMoves =    {['tl2']='tl3*',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4*',['s2']='s4*',['s3']='s4*',
                        ['br1']='br3',['br2']='br3',
                        ['tr2']='tr3*'},
        swerves =      {['tl2'] = {nil,'bl2'}, ['tl3*'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3*','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4*'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3*'},
                        ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil},
                        ['k4*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s1','s1','s1','s1','s2','s2'},
        alternate = "YGRE",
        alternateLevel = 6
    }
    AI_DEFS['DOTE']['YGRE'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['YGOL']))
    AI_DEFS['DOTE']['YGRE'].description = 'Grey Squadron Pilot'
    AI_DEFS['DOTE']['YGRE'].hasFreeFocus = true
    AI_DEFS['DOTE']['YGRE'].hasConditionalFocus = false
    AI_DEFS['DOTE']['YGRE'].elitePilotSkills = {4,5,6,8,10}
    -- AI_DEFS['DOTE']['YGRE'].elitePilotSkillDeckEntries = 2
    AI_DEFS['DOTE']['YGRE'].pilotCards = {'https://i.imgur.com/IKosfUo.png'}
    AI_DEFS['DOTE']['YGRE'].maneuverCard = 'https://i.imgur.com/T7FvHSp.png'
    AI_DEFS['DOTE']['YGRE'].alternate = nil
    AI_DEFS['DOTE']['YGRE'].alternateLevel = nil

    AI_DEFS['DOTE']['YSYN'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['YGOL']))
    AI_DEFS['DOTE']['YSYN'].shipType = 'Y-Wing Scum'
    AI_DEFS['DOTE']['YSYN'].faction = SCUM
    AI_DEFS['DOTE']['YSYN'].description = 'Syndicate Thug'
    AI_DEFS['DOTE']['YSYN'].diffuse = 'http://i.imgur.com/CB3arLi.jpg'
    AI_DEFS['DOTE']['YSYN'].closeMoves =   {{'bl1','br1','s1','s1','tl2','tr2'},
                                            {'tr2','tr2','s1','br1','br1','br1'},
                                            {'br1','tr2','tr2','tr2','tr3','tr3'},
                                            {'k4*','k4*','k4*','tr2','tr2','tr3'},
                                            {'k4*','k4*','k4*','tl2','tr2','s3'}}
    AI_DEFS['DOTE']['YSYN'].closeMoves =   {{'s4*','s3','s3','s3','s2','s2'},
                                            {'s2','br2','br3','br3','tr2','tr2'}, --assuming 2nd row of br2 is acutally br3
                                            {'br3','tr2','tr2','tr2','tr3','tr3'},
                                            {'k4*','k4*','tr2','tr2','tr2','tr3'},
                                            {'k4*','k4*','k4*','k4*','tl2','tr2'}}
    AI_DEFS['DOTE']['YSYN'].fleeMoves =    {['tl2']='tl3',
                                            ['bl1']='bl3',['bl2']='bl3',
                                            ['s1']='s4*',['s2']='s4*',['s3']='s4*',
                                            ['br1']='br3',['br2']='br3',
                                            ['tr2']='tr3' }
    AI_DEFS['DOTE']['YSYN'].swerves =      {['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                                            ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                                            ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4*'] = {'bl3','br3'},
                                            ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                                            ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                                            ['k4*'] = {'bl3','br3'} }
    AI_DEFS['DOTE']['YSYN'].hyperdriveMoves = {'s1','s2','s2','s3','tl3','tr3'}
    AI_DEFS['DOTE']['YSYN'].elitePilotSkills = {2,5,6,8,10}
    AI_DEFS['DOTE']['YSYN'].eliteLimits = {6,8,10}
    AI_DEFS['DOTE']['YSYN'].pilotCards = {'https://i.imgur.com/1PqXt9a.png'}
    AI_DEFS['DOTE']['YSYN'].elitePilotCards = {'https://i.imgur.com/3wvTPLf.png','https://i.imgur.com/IX19vrf.png'}
    AI_DEFS['DOTE']['YSYN'].maneuverCard = 'https://i.imgur.com/6AncNWj.png'
    AI_DEFS['DOTE']['YSYN'].alternate = 'YHIR'
    AI_DEFS['DOTE']['YSYN'].alternateLevel = 5

    AI_DEFS['DOTE']['YHIR'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['YSYN']))
    AI_DEFS['DOTE']['YHIR'].description = 'Hired Gun'
    AI_DEFS['DOTE']['YHIR'].diffuse = 'http://i.imgur.com/uDMHAL2.jpg'
    AI_DEFS['DOTE']['YHIR'].elitePilotSkills = {4,5,6,8,10}
    AI_DEFS['DOTE']['YHIR'].pilotCards = {'https://i.imgur.com/WSK0mDv.png'}
    AI_DEFS['DOTE']['YHIR'].maneuverCard = 'https://i.imgur.com/p7stZa5.png'
    AI_DEFS['DOTE']['YHIR'].alternate = nil
    AI_DEFS['DOTE']['YHIR'].alternateLevel = nil
    -- AI_DEFS['DOTE']['YHIR'].elitePilotSkillDeckEntries = 2

    --TODO: Scum has multiple erros (right most arc has tr3 and k3* that don't exist)
    AI_DEFS['DOTE']['HWK'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'HWK-290 Rebel',
        description = 'Rebel Operative',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029098250/4E8A65B9C156B7882A729BC9D93B2B434D549834/',
        diffuse = 'http://i.imgur.com/lOoTAem.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'A38D72',
        hasFreeFocus = true,
        hasConditionalTargetLock = true,
        elitePilotSkills = {2,nil,nil,nil,nil},
        elitePilotSkillDeckEntries = 0,
        pilotCards = {'https://i.imgur.com/o8L4r2y.png'},
        maneuverCard = 'https://i.imgur.com/dSNasyx.png',
        closeMoves =   {{'s3','s3','br2','bl2','tr2','tl2'},
                     -- {'s1','s1','br2','bl2','tr2','tl2'}, --SCUM VARIANT
                        {'br2','tl2','bl2','s3','s3','s4*'},
                     -- {'br2','tl2','br2','br2',s1','s1'}, --SCUM VARIANT
                        {'br3*','br2','br2','tr2','br1','br1'},
                        {'br3*','br2','br2','tr2','tr2','br1'},
                        {'tl2','tl2','tr2','tr2','bl1','br1'}},
        farMoves =     {{'s4*','s3','s3','s3','s2','s2'},
                        {'s4*','s3','br2','br2','tr2','br3*'},
                     -- {'s4*','br2','br2','tr2','br3*','br3*'}, --SCUM VARIANT
                        {'br3*','br2','br2','tr2','tr2','br1'},
                        {'tr2','tr2','tr2','tr2','br1','br1'},
                        {'tl2','tl2','tl2','tr2','tr2','tr2'}},
        fleeMoves =    {['bl1']='bl3*',['bl2']='bl3*',
                        ['s1']='s4*',['s2']='s4*',['s3']='s4*',
                        ['br1']='br3*',['br2']='br3*' },
        swerves =      {['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3*'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3*','br3*'}, ['s4*'] = {'bl3*','br3*'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3*'] = {'s3','tr2'},
                        ['tr2'] = {'br2',nil} },
        hyperdriveMoves = {'s1','s1','s2','s2','bl1','br1'}
    }
    AI_DEFS['DOTE']['HWKS'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['HWK']))
    AI_DEFS['DOTE']['HWKS'].faction = SCUM
    AI_DEFS['DOTE']['HWKS'].description = 'Spice Runner'
    AI_DEFS['DOTE']['HWKS'].hasFreeFocus = false
    AI_DEFS['DOTE']['HWKS'].hasConditionalFocus = true
    AI_DEFS['DOTE']['HWKS'].hasConditionalTargetLock = false
    AI_DEFS['DOTE']['HWKS'].elitePilotSkills = {1,nil,nil,nil,nil}
    AI_DEFS['DOTE']['HWKS'].diffuse = 'http://i.imgur.com/Hvu4B9m.jpg'
    AI_DEFS['DOTE']['HWKS'].pilotCards = {'https://i.imgur.com/2PuoffI.png'}
    AI_DEFS['DOTE']['HWKS'].maneuverCard = 'https://i.imgur.com/PMDXmhp.png'

    AI_DEFS['PALLAS']['ORS'] = HostileAiDefinition:new{ --YT-1300
        faction = EMPIRE, --REBELLION
        shipType = 'YT-1300',
        description = 'Mining Craft (Outer Rim Smuggler)',
        isLargeShip = true,
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029088151/213EF50E847F62BB943430BA93094F1E794E866B/',
        diffuse = 'http://i.imgur.com/QiomPcM.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964883/B11F61E5ED25B90F87C047EB6252D3B18EBB09F1/',
        typeColor = 'CAC8C6',
	    has360Turret = true,
	    hasFreeFocus = true,
	    hasConditionalFocus = false,
	    hasConditionalTargetLock = true,
	    elitePilotSkills = {1,nil,nil,nil,nil},
	    elitePilotSkillDeckEntries = 1,
        pilotCards = {'https://i.imgur.com/xWIEyzi.png'},
        maneuverCard = 'https://i.imgur.com/IYgZ3rH.png',
	    closeMoves = {{'s4','s4','bl3','br3','tr2','tl2'},
                      {'br3','bl3','bl2','tl2','s4','s4'},
                      {'br3','br3','br1','tr2','tr1','k4*'},
                      {'tr2','tr2','tr1','tr1','k3*','k4*'},
                      {'k4*','k4*','k4*','tl1','tr1','s1'}},
	    farMoves = {{'s4','s4','s4','s3','s3','s2'},
                    {'s4','br3','br3','br3','br2','tr2'},
                    {'br3','br3','tr2','tr2','br1','tr1'},
                    {'k4*','k3*','tr2','tr2','tr2','tr1'},
                    {'k4*','k3*','k3*','k3*','tl1','tr1'}},
	    fleeMoves = {['tl1'] = 'tl2',
                     ['bl1'] = 'bl3', ['bl2'] = 'bl3',
                     ['s1'] = 's4', ['s2'] = 's4', ['s3'] = 's4',
                     ['br1'] = 'br3', ['br2'] = 'br3',
                     ['tr1'] = 'tr2',
                     ['k4*'] = 'k3*' },
	    swerves = { ['tl1'] = {nil,'bl1'},   ['tl2'] = {nil,'bl2'},
                    ['bl1'] = {'tl1','s1'},  ['bl2'] = {'tl2','s2'},  ['bl3'] = {'tl2','s3'},
                    ['s1'] = {'bl1','br1'},  ['s2'] = {'bl2','br2'},  ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                    ['br1'] = {'s1','tr1'},  ['br2'] = {'s2','tr2'},  ['br3'] = {'s3','tr2'},
                    ['tr1'] = {'br1',nil },  ['tr2'] = {'br2',nil },
                    ['k3*'] = {'bl3','br3'}, ['k4*'] = {'bl3','br3'}},
        hyperdriveMoves = {'s1','s1','s2','s2','bl1','br1'}
    }
    AI_DEFS['DOTE']['ORS'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['PALLAS']['ORS']))
    AI_DEFS['DOTE']['ORS'].description = 'Outer Rim Smuggler'
    AI_DEFS['DOTE']['ORS'].faction = REBELLION

    AI_DEFS['DOTE']['WSF'] = HostileAiDefinition:new{ --YT-2400
        faction = REBELLION,
        shipType = 'YT-2400',
        description = 'Wild Space Fringer',
        isLargeShip = true,
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029079241/206F408212849DCBB3E1934A623FD7A8844AAE47/',
        diffuse = 'http://i.imgur.com/suojpQZ.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964883/B11F61E5ED25B90F87C047EB6252D3B18EBB09F1/',
        typeColor = 'B4A89A',
	    hasFreeFocus = true,
	    hasConditionalFocus = false,
	    hasConditionalTargetLock = true,
	    hasBarrelRoll = true,
	    elitePilotSkills = {2,nil,nil,nil,nil},
        pilotCards = {'https://i.imgur.com/e4Endmo.png'},
        maneuverCard = 'https://i.imgur.com/QN95je7.png',
	    closeMoves = {{'s4','s4','bl3','br3','tr2','tl2'},
                      {'br3','bl3','bl2','tl2','s4','s4'},
                      {'br3','br3','br1','tr2','tr1','k4*'},
                      {'br1','br1','tr1','tr1','tr2','k4*'},
                      {'k4*','k4*','k4*','tl1','tr1','s1'}},
	    farMoves =   {{'s4','s4','s4','s3','s3','s2'},
                      {'s4','br3','br3','br2','tr2','tr3'},
                      {'br3','br3','tr3','tr3','br1','tr1'},
                      {'k4*','tr3','tr2','tr2','tr2','tr1'},
                      {'k4*','k4*','tl1','tr1','tl2','tr2'}},
        fleeMoves =  {['tl1']='tl3',['tl2']='tl3',
                      ['bl1']='bl3',['bl2']='bl3',
                      ['s1']='s4',['s2']='s4',['s3']='s4',
                      ['br1']='br3',['br2']='br3',
                      ['tr1']='tr3',['tr2']='tr3' },
        swerves =    {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                      ['bl1'] = {'tl1','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                      ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                      ['br1'] = {'s1','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                      ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                      ['k4*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s1','s1','s2','s2','bl1','br1'}
    }


    AI_DEFS['DOTE']['APRO'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'A-Wing',
        description = 'Prototype Pilot',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029092256/19939432DC769A3B77BA19F2541C9EA11B72C73B/',
        diffuse = 'http://i.imgur.com/iS3L5eo.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '819076',
        hasBarrelRoll = true,
        hasConditionalEvade = true,
        elitePilotSkills = {1,5,6,8,10},
        eliteLimits = {6,8,10},
        pilotCards = {'https://i.imgur.com/RkLeenM.png'},
        elitePilotCards = {'https://i.imgur.com/CFL8B2v.png','https://i.imgur.com/oxzWSkS.png'},
        maneuverCard = 'https://i.imgur.com/ryOnn3D.png',
        closeMoves =   {{'bl2','br2','s2','s2','k5*','k5*'},
                        {'tr2','tr2','s1','br1','br1','br1'},
                        {'br1','tr2','tr2','tr3','k4*','k4*'},
                        {'k4*','k4*','k4*','tr2','tr2','tr3'},
                        {'k4*','k4*','k4*','tl2','tr2','s4'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'br3','tr2','tr2','tr2','tr3','tr3'},
                        {'k4*','k4*','tr2','tr2','tr2','tr3'},
                        {'k4*','k4*','k4*','k4*','tl2','tr2'}},
        fleeMoves =    {['tl1']='tl3',['tl2']='tl3',
                        ['bl2']='bl3',
                        ['s2']='s5',['s3']='s5',['s4']='s5',
                        ['br2']='br3',
                        ['tr1']='tr3',['tr2']='tr3',
                        ['k5*']='k3*' },
        swerves =      {['tl1'] = {nil,'bl2'}, ['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'}, ['s5'] = {'bl3','br3'},
                        ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                        ['tr1'] = {'br2',nil}, ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                        ['k3*'] = {'bl3','br3'}, ['k5*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s5','s5','tr2','tr2','tl2','tl2'},
        alternate = 'AGRE',
        alternateLevel = 4
    }
    AI_DEFS['DOTE']['AGRE'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['APRO']))
    AI_DEFS['DOTE']['AGRE'].description = 'Green Squadron Pilot'
    AI_DEFS['DOTE']['AGRE'].diffuse = 'http://i.imgur.com/iS3L5eo.jpg'
    AI_DEFS['DOTE']['AGRE'].hasFreeFocus = true
    AI_DEFS['DOTE']['AGRE'].hasConditionalFocus = false
    AI_DEFS['DOTE']['AGRE'].elitePilotSkills = {3,5,6,8,10}
    AI_DEFS['DOTE']['AGRE'].pilotCards = {'https://i.imgur.com/iZgzkdp.png'}
    AI_DEFS['DOTE']['AGRE'].maneuverCard = 'https://i.imgur.com/1Z26KWZ.png'
    AI_DEFS['DOTE']['AGRE'].alternate = nil
    AI_DEFS['DOTE']['AGRE'].alternateLevel = nil

    AI_DEFS['DOTE']['HSCS'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'M3-A Interceptor', -- (Heavy Scyk)
        description = 'Cartel Spacer',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029096648/6773CD675FA734358137849555B2868AC513801B/',
        diffuse = 'http://i.imgur.com/b5nDFtF.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '6e5552',
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        elitePilotSkills = {2,6,7,9,10},
        eliteLimits = {7,9,10},
        pilotCards = {'https://i.imgur.com/a38v7vz.png'},
        elitePilotCards = {'https://i.imgur.com/HAHKc2W.png', 'https://i.imgur.com/chV5cEW.png'},
        maneuverCard = 'https://i.imgur.com/7saJh9V.png',
        closeMoves =   {{'bl1','br1','k3*','k3*','k5*','k5*'},
                        {'tr1','tr2','br2','br2','k3*','k3*'},
                        {'br1','tr2','tr2','tr1','tr1','tr1'},
                        {'tr1','tr1','tr2','tr2','k3*','k5*'},
                        {'k3*','k3*','k3*','tl2','tr2','s4'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'br2','tr1','tr2','tr2','tr3','tr3'},
                        {'k3*','k3*','tr2','tr2','tr2','tr3'},
                        {'k3*','k3*','k3*','k3*','tl2','tr2'}},
        fleeMoves =    {['tl1']='tl2',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1']='tr2',
                        ['k5*']='k3*' },
        swerves =      {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1','s2'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s2','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['k3*'] = {'bl3','br3'}, ['k5*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s2','s2','s3','s3','bl1','br1'}
    }
    AI_DEFS['DOTE']['HSTP'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['HSCS']))
    AI_DEFS['DOTE']['HSTP'].description = 'Tansarii Point Veteran'
    AI_DEFS['DOTE']['HSTP'].diffuse = 'http://i.imgur.com/ojOpBFC.jpg'
    AI_DEFS['DOTE']['HSTP'].pilotCards = 'https://i.imgur.com/V2VD48t.png'
    AI_DEFS['DOTE']['HSTP'].maneuverCard = 'https://i.imgur.com/roY4URD.png'
    AI_DEFS['DOTE']['HSTP'].elitePilotSkills = {5,6,7,9,10}
    AI_DEFS['DOTE']['LSCS'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['HSCS']))
    AI_DEFS['DOTE']['LSCS'].shipType = 'M-3A Interceptor' -- (Light Scyk)'
    AI_DEFS['DOTE']['LSCS'].maneuverCard = 'https://i.imgur.com/0Atf7ZJ.png'
    AI_DEFS['DOTE']['LSCS'].elitePilotSkills = {1,nil,nil,nil,nil}

    AI_DEFS['DOTE']['FIR'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'Firespray-31 Scum',
        description = 'Mandalorian Mercenary',
        isLargeShip = true,
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029069521/B5F857033DD0324E7508645821F17B572BC1AF6A/',
        diffuse = 'http://i.imgur.com/UAViC3E.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964883/B11F61E5ED25B90F87C047EB6252D3B18EBB09F1/',
        typeColor = '505343',
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        elitePilotSkills = {5,6,7,9,10},
        eliteLimits = {7,9,10},
        pilotCards = {'https://i.imgur.com/qzuxUFq.png'},
        elitePilotCards = {'https://i.imgur.com/flOT1WI.png', 'https://i.imgur.com/uettPk1.png'},
        maneuverCard = 'https://i.imgur.com/GLZKEKl.png',
        closeMoves =   {{'k4*','k4*','bl1','br1','s1','s1'},
                        {'tl3','s2','tr2','tr2','br1','br1'},
                        {'br1','tr2','tr2','tr2','k3*','k3*'},
                        {'k4*','bl1','bl2','bl2','tl2','s1'},
                        {'k4*','s1','s1','s1','bl1','br1'}},
        farMoves =     {{'s4','s3','s3','s3','s2','s2'},
                        {'s4','br3','br3','br3','tr3','br2'},
                        {'br2','tr2','tr2','tr2','tr3','tr3'},
                        {'k4*','k4*','k3*','k3*','tr2','bl1'},
                        {'k4*','k4*','bl2','bl2','br2','br2'}},
        fleeMoves =    {['tl2']='tl3',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr2']='tr3',
                        ['k4*']='k3*' },
        swerves =      {['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                        ['k3*'] = {'bl3','br3'}, ['k4*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s1','s1','bl1','br1','s2','s2'}
    }

    AI_DEFS['DOTE']['PZEA'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'Protectorate Starfighter',
        description = 'Zealous Recruit',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/89352769138031546/C70B323524602140897D8E195C19522DB450A7E0/',
        diffuse = 'http://cloud-3.steamusercontent.com/ugc/89352769138161283/DD31149DF8FA0F877EA863643A1DFDFEEC90D0BF/',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '446178',
        elitePilotSkills = {1,4,6,8,10},
        eliteLimits = {6,8,10},
        pilotCards = {'https://i.imgur.com/AoETIMi.png'},
        elitePilotCards = {'https://i.imgur.com/2FLq8ll.png','https://i.imgur.com/n0xAOek.png'},
        maneuverCard = 'https://i.imgur.com/QRh3zPg.png',
        closeMoves =   {{'bl2','br2','s2','s2','k4*','k4*'},
                        {'tr1','tr2','tr2','br2','br2','k4*'},
                        {'tr1','tr1','tr2','tr2','k4*','k4*'},
                        {'tr2t*','tr2t*','tr2t*','k4*','tr2','tr1'},
                        {'tr2t*','tr2t*','tl2t*','tl2t*','tr2','tl2'}},
        farMoves =     {{'s5','s5','s4','s4','s4','s3'},
                        {'s2','br2','br3','br3','br3','tr3'},
                        {'tr3','tr3','tr2','tr2','tr1','tr1'},
                        {'tr2t*','tr2t*','k4*','tr2','tr2','tr1'},
                        {'tr2t*','tr2t*','tl2t*','tl2t*','tl1','tr1'}},
        fleeMoves =    {['tl1']='tl3',['tl2']='tl3',
                        ['bl2']='bl3',
                        ['s2']='s5',['s3']='s5',['s4']='s5',
                        ['br2']='br3',
                        ['tr1']='tr3',['tr2']='tr3' },
        swerves =      {['tl1'] = {nil,'bl2'}, ['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'}, ['s5'] = {'bl3','br3'},
                        ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                        ['tr1'] = {'br2',nil}, ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                        ['tl2t*'] = {nil,'bl2'},
                        ['k4*'] = {'bl3','br3'},
                        ['tr2t*'] = {'br2',nil} },
        hyperdriveMoves = {'bl2','bl2','br2','br2','tl2','tr2'},
        alternate = 'PCON',
        alternateLevel = 7
    }
    AI_DEFS['DOTE']['PCON'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['PZEA']))
    AI_DEFS['DOTE']['PCON'].description = 'Concord Dawn Veteran'
    AI_DEFS['DOTE']['PCON'].diffuse = 'http://cloud-3.steamusercontent.com/ugc/89352769138141306/EC532F6E04EBCBB97E10A49B09D0BDB0D5E2334C/'
    AI_DEFS['DOTE']['PCON'].elitePilotSkills = {3,4,6,8,10}
    AI_DEFS['DOTE']['PCON'].pilotCards = {'https://i.imgur.com/qikLAwX.png'}
    AI_DEFS['DOTE']['PCON'].maneuverCard = 'https://i.imgur.com/nuatq3y.png'
    AI_DEFS['DOTE']['PCON'].alternate = nil
    AI_DEFS['DOTE']['PCON'].alternateLevel = nil

    AI_DEFS['DOTE']['KZCA'] = HostileAiDefinition:new{ --KZCA Scum Kihraxz Cartel
        faction = SCUM,
        shipType = 'Kihraxz Fighter',
        description = 'Cartel Marauder',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029077425/6C88D57B03EF8B0CD7E4D91FED266EC15C614FA9/',
        diffuse = 'http://i.imgur.com/AKcnKWf.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = 'E1984F',
        hasConditionalFocus = true,
        elitePilotSkills = {2,6,7,9,10},
        eliteLimits = {7,9,10},
        pilotCards = {'https://i.imgur.com/eU8aKSh.png'},
        elitePilotCards = {'https://i.imgur.com/9mA85zS.png','https://i.imgur.com/A8wrUgQ.png'},
        maneuverCard = 'https://i.imgur.com/Uo7iUEj.png',
        closeMoves =   {{'bl1','br1','s3','s3','s3','k5*'},
                        {'tr2','br2','br1','br1','k5*','k5*'},
                        {'br1','tr1','tr1','tr1','k4*','k4*'},
                        {'k5*','k5*','k3*','tr1','tr1','tr2'},
                        {'k3*','k3*','k3*','tl2','tr2','s4'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','tr2'},
                        {'br2','tr2','tr2','tr2','tr1','tr1'},
                        {'k5*','k3*','k3*','tr2','tr2','tr1'},
                        {'k3*','k3*','k5*','k5*','tl1','tr1'}},
        fleeMoves =    {['tl1']='tl2',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1']='tr2',
                        ['k5*']='k4*' },
        swerves =      {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1','s2'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s2','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['k4*'] = {'bl3','br3'}, ['k5*'] = {'bl3','br3'} },
        hyperdriveMoves = {'bl1','bl1','br1','br1','bl2','br2'},
        alternate = 'KZBL',
        alternateLevel = 7
    }
    AI_DEFS['DOTE']['KZBL'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['KZCA'])) --KZBL Scum Kihraxz Black Sun
    AI_DEFS['DOTE']['KZBL'].description = 'Black Sun Ace'
    AI_DEFS['DOTE']['KZBL'].diffuse = 'http://i.imgur.com/U5mDYyJ.png'
    AI_DEFS['DOTE']['KZBL'].elitePilotSkills = {5,6,7,9,10}
    AI_DEFS['DOTE']['KZBL'].pilotCards = {'https://i.imgur.com/Yg3Bgwy.png'}
    AI_DEFS['DOTE']['KZBL'].maneuverCard = 'https://i.imgur.com/f5BwgNe.png'
    AI_DEFS['DOTE']['KZBL'].alternate = nil
    AI_DEFS['DOTE']['KZBL'].alternateLevel = nil

    AI_DEFS['DOTE']['SVEN'] = HostileAiDefinition:new{--SVEN Scum StarViper Black Sun Enforcer
        faction = SCUM,
        shipType = 'StarViper',
        description = 'Black Sun Enforcer',
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029085780/6B4B13CE7C78700EF474D06F44CEB27A14731011/',
        diffuse = 'http://i.imgur.com/4Vzoz48.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964332/9FA07C37B1615A416F306081D9152902A9BFE9EE/',
        typeColor = '4A365A',
        hasBarrelRoll = true,
        hasBoost = true,
        hasConditionalFocus = true,
        elitePilotSkills = {1,4,6,8,10},
        eliteLimits = {6,8,10},
        pilotCards = {'https://i.imgur.com/NoB4cSW.png'},
        elitePilotCards = {'https://i.imgur.com/IiSvFMu.png','https://i.imgur.com/pF1oCkA.png'},
        maneuverCard = 'https://i.imgur.com/hKoyb3c.png',
        closeMoves =   {{'bl3s*','br3s*','bl1','br1','s1','s1'},
                        {'bl3s*','bl3s*','br2','tr1','br1','br1'},
                        {'bl3s*','bl3s*','tr2','tr1','tr1','tr1'},
                        {'tr1','tr1','tr2','bl3s*','bl3s*','br3s*'},
                        {'bl3s*','bl3s*','br3s*','br3s*','tl2','tr2'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','s3'},
                        {'br3','br3','br2','tr2','tr2','tr1'},
                        {'bl3s*','bl3s*','tr2','tr2','tr1','tr1'},
                        {'bl3s*','bl3s*','br3s*','br3s*','tl1','tr1'}},
        fleeMoves =    {['tl1']='tl2',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1']='tr2' },
        swerves =      {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['bl3s*'] = {'tl2','s3'},
                        ['br3s*'] = {'s3','tr2'} },
        hyperdriveMoves = {'s1','s1','s2','s2','bl1','br1'},
        alternate = 'SVVI',
        alternateLevel = 8
    }
    AI_DEFS['DOTE']['SVVI'] = HostileAiDefinition:new(table.ShallowCopy(AI_DEFS['DOTE']['SVEN'])) --SVVI Scum StarViper Black Sun Vigo
    AI_DEFS['DOTE']['SVVI'].description = 'Black Sun Vigo'
    AI_DEFS['DOTE']['SVVI'].diffuse = "http://i.imgur.com/604dnbD.jpg"
    AI_DEFS['DOTE']['SVVI'].elitePilotSkills = {3,4,6,8,10}
    AI_DEFS['DOTE']['SVVI'].pilotCards = {'https://i.imgur.com/EhnVhPw.png'}
    AI_DEFS['DOTE']['SVVI'].maneuverCard = "https://i.imgur.com/fOjakJA.png"
    AI_DEFS['DOTE']['SVVI'].alternate = nil
    AI_DEFS['DOTE']['SVVI'].alternateLevel = nil

    AI_DEFS['DOTE']['JUMP'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'JumpMaster 5000',
        description = 'Contracted Scout',
        isLargeShip = true,
        mesh = 'http://cloud-3.steamusercontent.com/ugc/82591194029067863/A8F7079195681ECD24028AE766C8216E6C27EE21/',
        diffuse = 'http://i.imgur.com/D58bZNz.jpg',
        collider = 'http://cloud-3.steamusercontent.com/ugc/856097073971964883/B11F61E5ED25B90F87C047EB6252D3B18EBB09F1/',
        typeColor = 'B06C73',
        hasFreeFocus = true,
        hasConditionalFocus = false,
        hasBarrelRoll = true,
        hasConditionalTargetLock = true,
        elitePilotSkills = {3,4,6,8,10},
        eliteLimits = {6,8,10},
        pilotCards = {'https://i.imgur.com/8RGysEY.png'},
        elitePilotCards = {'https://i.imgur.com/nuX5vUK.png','https://i.imgur.com/v3UZO0j.png'},
        maneuverCard = 'https://i.imgur.com/oHFQpVX.png',
        closeMoves =   {{'k4*','k4*','bl2s','bl2s','br2s*','s1'},
                        {'k4*','br2s*','br2s*','tr1','br1','br1'},
                        {'br2s*','br2s*','tr2','tr1','tr1','tr1'},
                        {'tr1','tr1','tr2','br2s*','br2s*','bl2s'},
                        {'k4*','bl2s','bl2s','br2s*','tl2','tl2'}},
        farMoves =     {{'s4','s4','s3','s3','s3','s2'},
                        {'s2','br2','br3','br3','br3','s3'},
                        {'br3','br3','br2','tr2','tr2','tr1'},
                        {'bl2s','bl2s','tr2','tr2','tr1','tr1'},
                        {'k4*','k4*','bl2s','bl2s','br2s*','tl1'}},
        leftAlts =     {['bl2s*'] = 'bl2s',
                        ['br2s'] = 'br2s*' },
        fleeMoves =    {['tl1']='tl2',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1']='tr2' },
        swerves =      {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['bl2s'] = {'tl2','k4*'},
                        ['k4*'] = {'bl2s','br2s*'},
                        ['br2s*'] = {'k4*','tr2'} },
        hyperdriveMoves = {'s1','s2','bl1','bl1','br1','br1'}
    }
    --TODO: Lancer
    --mesh: https://paste.ee/r/1af5C
    --diffuse: http://i.imgur.com/D58bZNz.jpg
    --collider: https://paste.ee/r/v8OYL
    AI_DEFS['MISC']['LANC'] = HostileAiDefinition:new{ --Extra ships
        faction = SCUM,
        shipType = 'Lancer-class Pursuit Craft',
        description = 'Shadowport Hunter',
        isLargeShip = true,
        mesh = 'https://paste.ee/r/1af5C',
        diffuse = 'http://i.imgur.com/D58bZNz.jpg',
        collider = 'https://paste.ee/r/v8OYL',
        typeColor = '9E8C2E',
        hasFreeTargetLock = true,
        --TODO: mobileFiringArc?
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        elitePilotSkills = {2,nil,nil,nil,nil},
        pilotCards = {'https://i.imgur.com/XuPL43P.jpg'},
        maneuverCard = 'https://i.imgur.com/1OVn26o.png',
        closeMoves =   {{'bl1','bl1','br1','br1','s1','k5*'},
                        {'tr2','bl3','bl3','s1','s1','k5*'},
                        {'tl2','bl2','bl2','tr3','tr3','k5*'},
                        {'k5*','k5*','tr2','tr3','tr3','br1'},
                        {'tr3','tr3','tl3','tl3','k5*','s5'}},
        farMoves =     {{'s5','s5','s5','s4','s4','s3'},
                        {'s2','bl2','tr3','tr3','br3','br3'},
                        {'br3','br3','tr3','tr3','tr2','tr2'},
                        {'k5*','k5*','tr2','tr2','tr3','tr3'},
                        {'k5*','k5*','tl2','tl2','tr2','tr2'}},
        fleeMoves =    {['tl2']='tl3',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s5',['s2']='s5',['s3']='s5',['s4']='s5',
                        ['br1']='br3',['br2']='br3',
                        ['tr2']='tr3' },
        swerves =      {['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'}, ['s5'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                        ['k5*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s3','s4','tl3','bl3','br3','tr3'}
    }

    --TODO: G-1A Starfighter
    AI_DEFS['MISC']['MIST'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'G-1A StarFighter',
        description = 'Ruthless Freelancer',
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = '57302F',
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        elitePilotSkills = {3,nil,nil,nil,nil},
        pilotCards = {'https://i.imgur.com/0pG7odQ.png'},
        maneuverCard = 'https://i.imgur.com/UnntyMT.png',
        closeMoves =   {{'bl1','bl1','br1','br1','s1','s1'},
                        {'tr2','br1','br1','s1','s1','k4*'},
                        {'tr2','br2','br2','tr1*','tr1*','k4*'},
                        {'k4*','k4*','tr2','tr2','tr1*','tr1*'},
                        {'tl2','tl2','tr2','tr2','k4*','k3*'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','br2','tr2','tr2','br3*','br3*'},
                        {'br3*','br3*','tr1*','tr1*','tr2','tr2'},
                        {'k3*','k3*','tr2','tr2','tr1*','tr1*'},
                        {'k3*','k3*','tl2','tl2','tr2','tr2'}},
        fleeMoves =    {['tl1*']='tl2',
                        ['bl1']='bl3*',['bl2']='bl3*',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3*',['br2']='br3*',
                        ['tr1*']='tr2',
                        ['k4*']='k3*' },
        swerves =      {['tl1*'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1*','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3*'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3*','br3*'}, ['s4'] = {'bl3*','br3*'},
                        ['br1'] = {'s1','tr1*'}, ['br2'] = {'s2','tr2'}, ['br3*'] = {'s3','tr2'},
                        ['tr1*'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['k3*'] = {'bl3*','br3*'}, ['k4*'] = {'bl3*','br3*'} },
        hyperdriveMoves = {'s1','s2','s3','s3','bl1','br1'}
    }

    --TODO: ARC-170
    AI_DEFS['MISC']['ARC'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'ARC-170',
        description = 'Razor Squadron Pilot',
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = 'BB7071',
        elitePilotSkills = {3,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        pilotCards = {'https://i.imgur.com/ejN4xWf.png'},
        maneuverCard = 'https://i.imgur.com/DfPD5Aj.png',
        closeMoves =   {{'s1','s1','bl1','br1','s2','k4*'},
                        {'s1','br2','br2','br1','br1','k4*'},
                        {'tr2','tr2','tr2','k4*','k4*','tr3*'},
                        {'br1','br1','tr2','tr2','tr3*','k4*'},
                        {'k4*','k4*','tr2','tl2','br3','bl3'}},
        farMoves =     {{'s4*','s4*','s4*','s3','s3','s2'},
                        {'s2','tr3*','br3','br3','br2','br2'},
                        {'br3','br2','tr3*','tr3*','tr2','tr2'},
                        {'br3','tr2','tr3*','tr3*','k4*','k4*'},
                        {'k4*','k4*','tr2','tr2','tl2','tl2'}},
        fleeMoves =    {['tl2']='tl3*',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4*',['s2']='s4*',['s3']='s4*',
                        ['br1']='br3',['br2']='br3',
                        ['tr2']='tr3*' },
        swerves =      {['tl2'] = {nil,'bl2'}, ['tl3*'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3*','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4*'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3*'},
                        ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil},
                        ['k4*'] = {'bl3','br3'} },
        hyperdriveMoves = {'bl1','s1','br1','bl2','s2','br2'}
    }

    --TODO: YV-666
    AI_DEFS['MISC']['YVS'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'YV-666',
        description = 'Trandoshan Slaver',
        isLargeShip = true,
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = 'A77946',
        elitePilotSkills = {2,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        pilotCards = {'https://i.imgur.com/z5eEZCf.png'},
        maneuverCard = 'https://i.imgur.com/OM6lTsj.png',
        closeMoves =   {{'s1','bl1','br1','s0*','s0*','s0*'},
                        {'s1','br2','br1','br1','br1','s0*'},
                        {'br2','br1','br1','tr2*','tr2*','s0*'},
                        {'br3','tr3','tr3','tr2*','br2','s0*'},
                        {'s0*','s0*','tr3','tl3','br3','bl3'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','br2','br3','br3','tr3','tr3'},
                        {'br3','br2','tr2*','tr2*','tr3','tr3'},
                        {'br3','br1','tr2*','tr2*','tr3','tr3'},
                        {'tl2*','tl2*','tl2*','tr2*','tr2*','tr2*'}},
        fleeMoves =    {['tl2*']='tl3',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s0*']='s4',['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr2*']='tr3' },
        swerves =      {['tl2*'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2*','s1'}, ['bl2'] = {'tl2*','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s0*'] = {'bl1','br1'}, ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2*'}, ['br2'] = {'s2','tr2*'}, ['br3'] = {'s3','tr3'},
                        ['tr2*'] = {'br2',nil}, ['tr3'] = {'br3',nil} },
        hyperdriveMoves = {'s1','s1','bl1','br1','s2','s3'}
    }

    --TODO: Attack Shuttle
    AI_DEFS['MISC']['AS'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'Attack Shuttle',
        description = 'VCX-Series Auxiliary Starfighter',
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = '717171',
        elitePilotSkills = {3,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasBarrelRoll = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        pilotCards = {'https://i.imgur.com/tsCVD1A.png'},
        maneuverCard = 'https://i.imgur.com/7gAwUlP.png',
        closeMoves =   {{'s1','s1','bl1','br1','k4*','k4*'},
                        {'s1','k4*','k4*','br2','br2','br1'},
                        {'tr1*','tr1*','tr1*','br2','br2','tr2'},
                        {'k4*','k4*','tr2','tr2','tr1*','tr3*'},
                        {'k4*','k4*','tr2','tr2','tl2','tl2'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','tr3*','br3','br3','br2','br2'},
                        {'br3','br2','tr3*','tr3*','tr2','tr2'},
                        {'br2','tr2','tr3*','tr3*','k4*','k4*'},
                        {'k4*','k4*','tr2','tr2','tl2','tl2'}},
        fleeMoves =    {['tl1*']='tl3*',['tl2']='tl3*',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1*']='tr3*',['tr2']='tr3*' },
        swerves =      {['tl1*'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'}, ['tl3*'] = {nil,'bl3'},
                        ['bl1'] = {'tl1*','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3*','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr1*'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3*'},
                        ['tr1*'] = {'br1',nil}, ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil},
                        ['k4*'] = {'bl3','br3'} },
        hyperdriveMoves = {} --NO HYPERDRIVE
    }

    --TODO: VCX-100
    AI_DEFS['MISC']['VCX'] = HostileAiDefinition:new{
        faction = REBELLION,
        shipType = 'VCX-100',
        description = 'Lothal Rebel',
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = '',
        elitePilotSkills = {3,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        pilotCards = {'https://i.imgur.com/acu3O5f.png'},
        maneuverCard = 'https://i.imgur.com/vNMKEx1.png',
        closeMoves =   {{'s1','s1','bl1','br1','k5*','k5*'},
                        {'s1','k5*','k5*','br2','br2','br1'},
                        {'tr1*','tr1*','tr1*','br2','br2','tr2'},
                        {'br1','br1','tr2','tr2','tr1*','k5*'},
                        {'k5*','k5*','tr2','tl2','br3','bl3'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s2','tr3*','br3','br3','br2','br2'},
                        {'br3','br2','tr3*','tr3*','tr2','tr2'},
                        {'br2','tr2','tr3*','tr3*','k5*','k5*'},
                        {'k5*','k5*','tr2','tr2','tl2','tl2'}},
        fleeMoves =    {['tl1*']='tl3*',['tl2']='tl3*',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr1*']='tr3*',['tr2']='tr3*' },
        swerves =      {['tl1*'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'}, ['tl3*'] = {nil,'bl3'},
                        ['bl1'] = {'tl1*','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3*','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr1*'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3*'},
                        ['tr1*'] = {'br1',nil}, ['tr2'] = {'br2',nil}, ['tr3*'] = {'br3',nil},
                        ['k5*'] = {'bl3','br3'} },
        hyperdriveMoves = {'s1','s2','bl2','bl2','br2','br2'}
    }

    --TODO: Aggressor (IG-88)
    --maneuverCard = 'https://i.imgur.com/KsUgPNn.png'
    AI_DEFS['MISC']['AGGR'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'Aggressor',
        description = 'IG-88',
        isLargeShip = true,
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = '354AAE',
        elitePilotSkills = {6,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasBoost = true,
        hasConditionalFocus = true,
        hasConditionalEvade = true,
        pilotCards = {'https://i.imgur.com/gOnNNnb.png'},
        maneuverCard = 'https://i.imgur.com/peaW8gf.png',
        closeMoves =   {{'bl3s*','br3s*','bl1','br1','s1','k4*'},
                        {'s1','bl3s*','br1','br1','br1','k4*'},
                        {'bl3s*','tr1','tr1','tr2','tr2','k4*'},
                        {'bl3s*','br3s*','tr1','tr1','k4*','k4*'},
                        {'bl3s*','br3s*','k4*','k4*','tl1','tr1'}},
        farMoves =     {{'s3','s3','s3','s3','s2','s2'},
                        {'s2','br2','br2','br3','br3','br1'},
                        {'br2','tr2','tr2','tr1','tr1','br1'},
                        {'k4*','k4*','bl3s*','tr2','tr2','tr1'},
                        {'k4*','k4*','bl3s*','br3s*','tl2','tr2'}},
        fleeMoves =    {['tl1']='tl2',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s3',['s2']='s3',
                        ['br1']='br3',['br2']='br3',
                        ['tr1']='tr2' },
        swerves =      {['tl1'] = {nil,'bl1'}, ['tl2'] = {nil,'bl2'},
                        ['bl1'] = {'tl1','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl2','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr1'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr2'},
                        ['tr1'] = {'br1',nil}, ['tr2'] = {'br2',nil},
                        ['bl3s*'] = {'tl2','k4*'},
                        ['k4*'] = {'bl3s*','br3s*'},
                        ['br3s*'] = {'k4*','tr2'} },
        hyperdriveMoves = {'bl2','bl3','s2','s3','br2','br3'}
    }

    --TODO: T-70 X-Wing
    AI_DEFS['MISC']['XTBL'] = HostileAiDefinition:new{
        faction = SCUM,
        shipType = 'T-70 X-Wing',
        description = 'Blue Squadron Novice',
        mesh = '',
        diffuse = '',
        collider = '',
        typeColor = '',
        elitePilotSkills = {2,nil,nil,nil,nil},
        hasFreeTargetLock = true,
        hasBoost = true,
        hasConditionalFocus = true,
        pilotCards = {'https://i.imgur.com/SrjWBvJ.png'},
        maneuverCard = 'https://i.imgur.com/im9z3zX.png',
        closeMoves =   {{'k4*','k4*','bl1','br1','s2','s1'},
                        {'s1','tl3t*','br1','br1','br1','k4*'},
                        {'br1','tr2','tr2','tl3t*','tl3t*','k4*'},
                        {'k4*','k4*','br1','tr2','tr2','tl3t*'},
                        {'s4','k4*','k4*','k4*','tl3t*','tr3t*'}},
        farMoves =     {{'s4','s4','s4','s3','s3','s2'},
                        {'s3','br2','br3','br3','tr3','tr2'},
                        {'br1','br2','tr2','tr2','tr3','tr3'},
                        {'k4*','k4*','tr3t*','tr3t*','tr3t*','tr2'},
                        {'k4*','k4*','tl3t*','tr3t*','tl2','tr2'}},
        fleeMoves =    {['tl2']='tl3',
                        ['bl1']='bl3',['bl2']='bl3',
                        ['s1']='s4',['s2']='s4',['s3']='s4',
                        ['br1']='br3',['br2']='br3',
                        ['tr2']='tr3' },
        swerves =      {['tl2'] = {nil,'bl2'}, ['tl3'] = {nil,'bl3'},
                        ['bl1'] = {'tl2','s1'}, ['bl2'] = {'tl2','s2'}, ['bl3'] = {'tl3','s3'},
                        ['s1'] = {'bl1','br1'}, ['s2'] = {'bl2','br2'}, ['s3'] = {'bl3','br3'}, ['s4'] = {'bl3','br3'},
                        ['br1'] = {'s1','tr2'}, ['br2'] = {'s2','tr2'}, ['br3'] = {'s3','tr3'},
                        ['tr2'] = {'br2',nil}, ['tr3'] = {'br3',nil},
                        ['tl3t*'] = {nil,'bl3'},
                        ['k4*'] = {'bl3','br3'},
                        ['tr3t*'] = {'br3',nil} },
        hyperdriveMoves = {'bl1','br1','s1','s2','s3','s3'}
    }

    -- AI_DEFS['MISC'][''] = HostileAiDefinition:new{
    --     faction = SCUM,
    --     shipType = '',
    --     description = '',
    --     mesh = '',
    --     diffuse = '',
    --     collider = '',
    --     typeColor = '',
    --     elitePilotSkills = {3,nil,nil,nil,nil},
    --     eliteLimits = {7,9,10},
    --     pilotCards = {''},
    --     elitePilotCards = {''},
    --     maneuverCard = '',
    --     alternate = nil,
    --     alternateLevel = nil,
    --     closeMoves =   {{},
    --                     {},
    --                     {},
    --                     {},
    --                     {}},
    --     farMoves =     {{},
    --                     {},
    --                     {},
    --                     {},
    --                     {}},
    --     fleeMoves =
    --     swerves =
    --     hyperdriveMoves = {}
    -- }

    -- Spawn custom cards?
    -- '{ "Hands": true, "CardID": '..(100+card_zero_index)..
    -- ', "SidewaysCard": false, "CustomDeck": { "1": { "FaceURL": "'..faceURL..
    -- '", "BackURL": "'..backURL..
    -- '", "NumWidth": '..numWidth..
    -- ', "NumHeight": '..numHeight..
    -- ', "BackIsHidden": false, "UniqueBack": true } } }'
    for _,campaign_key in ipairs(campaigns) do
        local offset = 0
        for key,ai in pairs(AI_DEFS[campaign_key]) do
            --printToAll("Mirroring: "..campaign_key.." "..key,{1,1,1})
            mirrorMoveTable(ai.closeMoves,ai.leftAlts)
            mirrorMoveTable(ai.farMoves,ai.leftAlts)
            -- pilot_card_offsets[campaign] = {}
            pilot_card_offsets[campaign_key][key] = offset
            offset = offset + ai.elitePilotSkillDeckEntries
            -- pilot_card_num[campaign] = {}
            pilot_card_num[campaign_key][key] = ai.elitePilotSkillDeckEntries
            -- squad_types_deck[campaign] = {}
            for i=1,ai.elitePilotSkillDeckEntries do
                table.insert(squad_types_deck[campaign_key],key)
            end
            escaped_name = string.gsub(ai.shipType,"[%.%s-%/]","")
            table.insert(SHIP_TYPES, escaped_name)
        end
    end
    -- AI_DEFS['TEMP'] = HostileAiDefinition:new{
    --     isLargeShip = false,
    --     mesh = '',
    --     diffuse = '',
    --     collider = '',
    --     typeColor = 'FFFFFF',
    --     has360Turret = false,
    --     hasCloak = false,
    --     hasFreeFocus = false,
    --     hasFreeEvade = false,
    --     hasFreeTargetLock = false,
    --     hasFreeBarrelRoll = false,
    --     hasBoost = false,
    --     hasBarrelRoll = false,
    --     hasConditionalFocus = true,
    --     hasConditionalEvade = false,
    --     hasConditionalTargetLock = false,
    --     elitePilotSkills = {},
    --     elitePilotSkillDeckEntries = 0,
    --     closeMoves = {},
    --     farMoves = {},
    --     fleeMoves = {},
    --     swerves = {}
    -- }
end
function findDefByName(campaign, name)
    for k, def in pairs(AI_DEFS[campaign]) do
        if def.shipType==name then
            return def
        end
    end
    for _, camp in pairs(AI_DEFS) do
        for _, def in pairs(camp) do
            if def.shipType==name then
                return def
            end
        end
    end
    return {}
end
